### ISSUE TITLE
The Miscellaneous Issues/Questions Page 

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#133]
Important stuff:
1.The SplashesHelper is not registered anywhere.
2.EventHandlerDrawHighlight does what exactly?
3.What does the ItemMonocle do?
4.Is ItemGuideBook obsolete?
5.What does the ItemLightningGun do?
6.Is ItemParts class still used?
7.What is the ItemPipe class?
8.What is the ItemSpanner?
9.Do we still implement the ItemTeaSeed?
10.What is EntitySmallLightningBolt used for?
11.What is EntityPlayerExtended?

If any of the answers to the above question is "idk", please delete the class and all references.Thank you :)

Other stuff:
1.Can you please add a comment with the ingot names and metadata to ItemIngot class?

**Comment by warlordjones** [comment]
Gonna close this to clean the issue tracker a bit
