### ISSUE TITLE
Compatibility for spanner and machines with APIs

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#138]
It seems like the wrench and the machines do not work with the wrench from Cofh.
Also the spanner doesn't work as a Cofh wrench neither.

The Spanner however does work as a BC wrench, so that at least works, mainly because the BC API is more straight forward.

The spanner doesn't work as an IC2 wrench neither.Since there is no API for a wrench, I have to look into the source and see how IC2 does it.

The IC2 wrench does work on the machines, but only those with inventory.It's a design choice I made, maybe should add this to all machines.

**Comment by warlordjones** [comment]
Well, the wrench is pretty much universally compatible, from EIO to RC, so I'm closing this for now
