### ISSUE TITLE
Tier Two Pipes/Wires

### ISSUE THREAD

**Issue by warlordjones** [BrassGoggledCoders/SteamCraft2#156]
'High-Pressure Pipe' Transports a lot of fluid. Must use a 'Compressor' Machine to connect normal pipes to the high-pressure. The compressor is by default set to compress, but right-clicking with a spanner should set it to decompress, allowing the fluid to be put back into normal pipes. Thicker than a normal pipe.

'High Voltage Wire' Same as the pipe, but has a 'transformer' machine. Looks like a glass pipe, and has 'lightning' inside when transferring energy. (A little bit like fiber optic :P)

**Comment by warlordjones** [comment]
I'll keep this issue open since it's assigned to Decebal

**Comment by warlordjones** [comment]
After some further thought on how to implement this system, I'm thinking that we make the tier two wires/pipes only connect the the compressor/transformer, and they then need to be used as a bridge between the wires/pipes and anything else. I indend them only to be used as a high volume transfer method, not for powering machines, so I think this may be the best way of working it.

**Comment by decebaldecebal** [comment]
Sound cool and not that hard to implement :)

**Comment by warlordjones** [comment]
Good good :D I'm thinking glassfiber with energy beam for the tier 2 wires, and just bigger pipes for the tier 2 pipes XD I'll make a model for the transformer too at some point.

**Comment by decebaldecebal** [comment]
After thinking about it, the current system has a bottleneck per block, so a machine that transforms from one pipe to another of higher density is useless, cause the current pipes can transfer and unlimited amount through a path, they are only bottlenecked by the transfer per face...

So I don't think that implementing a Compressor/Transformer is a viable option cause it simply won't do anything...I think we should implement a higher tier of pipes/wires that can transfer more power/liquid per side, and be bigger than the current ones and the wires with an energy beam in them.

**Comment by warlordjones** [comment]
Ok, sounds good.

**Comment by decebaldecebal** [comment]
Should the pipes/wires be made of steel?Or other material?I just want to know to balance them properly.I think steel is a good material and they will be like a mid tier conduits, not capable of transferring insane amounts of energy and fluid, but moderate ones that should be enough to run most machines, but not quite handle a big reactor :)

**Comment by warlordjones** [comment]
Sounds good to me.

**Comment by decebaldecebal** [comment]
Steel Pipes/Wires are now added.
