### ISSUE TITLE
[Suggestion] Allow reverting ingots back to dust

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#165]
I thought I could smelt up my leftover dust into ingots and turn it back into dust later if I needed to but of course the hammer just turns it into plates. Usually not a big deal in tech modpacks that have pulverizers and such but I'm using this in a magic pack so I have no way to re-pulverize it.

**Comment by TekHed** [comment]
Definitely +1 for this. I think you should be able to smash ingots back to dust using the hammer, especially since it's not very clear at the beginning that the only way to get dust is from raw ores.

**Comment by warlordjones** [comment]
I fixed this in 6370b92d8da905d4ad0d91eab5a4e7634d578c7a
