### ISSUE TITLE
[Help] Lost on how to turn steam into RF

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#166]
Hi,

I'm a bit of a loss as to how to turn steam into RF, or more specifically how to create the magnets needed for the steam-powered turbine. In order to create magnets you need a jar filled with electrodes. As far as I can tell, the only thing that creates energy prior to getting your first steam-powered turbine is the lightning rod. I've got that set up, and WAILA shows that the lightning strikes have given it power, but I can't seem to move the power from the lightning rod into any other block (ie, the charger or the battery bank). I've tried putting it directly underneath the lightning rod with no copper wires, I've tried it a few blocks away from all sides *with* copper wires, with both ends of the wire wrenched, with neither, with either one wrenched. Nothing seems to pull the power out of the lightning rod. I noted that you can put a Telsa Coil directly underneath the lightning rod and it takes out the energy just fine, but that's not exactly gonna help me get a battery for a steam-powered turbine.

So am I missing something here? How do you get your first steam-powered boiler?

**Comment by HCSarise** [comment]
Update: turns out it works with copper wire from the side of the lightning rod, but not the bottom. However it doesn't really seem intuitive to have it coming from the side and not the bottom.

**Comment by warlordjones** [comment]
Should be the bottom...?

**Comment by HCSarise** [comment]
Okay, it seems to be working now for whatever reason (from the bottom as well). Bizarre, I'm positive it wasn't working before. The only thing I can think is I updated Forge.

**Comment by warlordjones** [comment]
Hmm, we (or rather the RF api) use ForgeDirection to determine which direction energy can be input/extracted, so perhaps that was the problem. Good to know you solved the problem, and sorry I was not more helpful, I've kind of put this project into hibernation to concentrate on upcoming exams. Dev will be coming back fullspeed soon!
