### ISSUE TITLE
Client Crash when extracting Liquid XP from a tank with Copper PIpes

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#169]
Crash Report:
https://gist.github.com/mallrat208/d13a994bf01bb966fbcd

SteamCraft 2 version B3.3b, Forge 1277

When attempting to extract Liquid XP as well as a few other Mod fluids from a Tank using Copper Pipes, I get a client crash like above.

The line that the NPE happens at is at Ln 147 in TileCopperPipeRenderer. The same bit of code that errors is also repeated at Ln 540
`IIcon icon = pipe.fluidInPipe.getBlock().getIcon(0, 0);` 

I was able to fix the crash by replacing those lines with the following
`IIcon icon = pipe.fluidInPipe.getIcon();`

**Comment by MrIbby** [comment]
Arona needs to learn how to properly [close issues via commit](https://help.github.com/articles/closing-issues-via-commit-messages/)...

**Comment by warlordjones** [comment]
Whoops, lol, I promise I can do this properly (see #71 :P) I just made a derp xP
