### ISSUE TITLE
[Suggestion] TiCon compatability

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#170]
Hi guys,

Could you please make your metals smeltable in the TiCon smeltery? Apologies if you're not the right ones to ask - I'll take it to TiCon devs if it's their responsibility.

Thanks

**Comment by warlordjones** [comment]
The copper, aluminum and tin should all work through the ore dictionary. The other metals I am planning to make compatible at some point.

**Comment by warlordjones** [comment]
Some work done in this in a399e6829160522719d0c99622c8d2e28a5b6864 and 6cbbbf446b97c335520f195229b6b6f2c759eedd

**Comment by warlordjones** [comment]
Complete in dev with the recent addition of molten zinc. Needs textures still, as most other stuff in B4 does.
