### ISSUE TITLE
Can't charge ray gun?

### ISSUE THREAD

**Issue by TekHed** [BrassGoggledCoders/SteamCraft2#171]
MC 1.7.10 with Forge 10.13.2.1264
Steamcraft 2 latest
Also running Buildcraft 6.2.6, Railcraft 9.4.0.0, and other usual stuff that shouldn't matter like NEI/WAILA, Optifine, whatever.

No matter what I do, can't charge ray guns in charger block. Charger is powered, and I can charge drills no problem. Seeing as there's zero information anywhere about this mod and the wiki is basically empty, I also tried other things like having electric jars of various tiers in my inventory, equipped in hotbar, etc. Nothing works.

**Comment by warlordjones** [comment]
Hmmmm, there's a bug! I'll look into this

**Comment by warlordjones** [comment]
I did dun screwed up :P
