### ISSUE TITLE
Duplicate recipes?

### ISSUE THREAD

**Issue by TekHed** [BrassGoggledCoders/SteamCraft2#172]
Here's a few other problems. There's no way to craft basic plating module for brass armor because the 9 steel ingots just makes a steel block (Maybe it's plates not ingots?). You also can't craft the fan required to make the steam turbine because the 5 ingot cross recipe makes a sprocket (again, it should be plates for fans?). Is NEI simply displaying the wrong recipe...

This is a really great mod with tons of potential but it needs work. I'm trying to start a steampunk server and Steamcraft2 works very very well alongside Buildcraft and Railcraft, but this mod doesn't feel finished enough to go. I'm willing to contribute how I can, please let me know if there's anything I can do. Maybe I'll start with updating the wiki?

**Comment by warlordjones** [comment]
I accidentally ore dictionaried steel ingots and steel plates as equivalent in the currently released version, I already fixed that.

It's not finished enough to go, that's why it's still beta! Updating the wiki would be great, ask me if you have any questions.

**Comment by warlordjones** [comment]
Hmm, I'll close this to get it off the issue tracker, as said, it's fixed for next version
