### ISSUE TITLE
Crash when placing a light down

### ISSUE THREAD

**Issue by crunkazcanbe** [BrassGoggledCoders/SteamCraft2#175]
I just downloaded the new version today , and still get the same crash as the last version when placing a light down .

http://pastebin.com/cwH9nkNY

**Comment by warlordjones** [comment]
Well, I certainly done screwed up somewhere. Will investigate when I get time.

**Comment by MrIbby** [comment]
It seems that the tile entity isn't registered.

**Comment by crunkazcanbe** [comment]
When i place the light down it will crash but when i start minecraft back up and start my world back the light is placed down where i put it . :/

**Comment by warlordjones** [comment]
Whoops, this was fixed in 523ccfddd19a41400682abf981ec7f13f85fb19c
