### ISSUE TITLE
[Bug] Copper wire won't connect to lightning rod.

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#176]
In the newest update, copper wire won't connect to the lightning rod from any direction.

**Comment by warlordjones** [comment]
Oh dear

**Comment by warlordjones** [comment]
I half updated to the new RF api, but failed. I need to do a little bit of changing to the energy system's internals.

**Comment by warlordjones** [comment]
Hopefully I don't break all the things...
