### ISSUE TITLE
Update GitHub whenever an update is released

### ISSUE THREAD

**Issue by MrIbby** [BrassGoggledCoders/SteamCraft2#180]
Each time a new version is released, [mark it on GitHub](https://github.com/BrassGoggledCoders/SteamCraft2/releases/new).

**Comment by warlordjones** [comment]
I guess I should get into the habit of doing this.

**Comment by warlordjones** [comment]
There, will do this from the latest version, if I remember. Done for 3.5. I won't upload binaries, I'd like to keep all downloads central to curse.
