### ISSUE TITLE
[Suggestion] Power compatability with other RF mods

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#181]
Hiya,

I just tried using Ender IO's power conduits to extract power from the lightning rod and it didn't seem to work, even though it visually connected. Could you guys have a look at adding compatibility for other mod's RF conduits?

**Comment by warlordjones** [comment]
Hmmm, it certainly used to work with TE conduits. I'll certainly look at it, no promises though :p

**Comment by warlordjones** [comment]
This is due to a recent RF api update, which we are updated to, but others are not, like ender IO. These issues will sort themselves out once all the mods are on the same RF api version - or should.
