### ISSUE TITLE
Sided selection for extracting mode

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#182]
Hiya,

Could you make it so we could select which side of the pipe/wire we want to be extracting from? For example when connecting a lightning rod to something else you end up needing 2 spaces worth of copper wire because otherwise it tries to extract from the other machine/block instead of the lightning rod.

**Comment by warlordjones** [comment]
I can ask decebal to look at this, I'm not sure I can do this myself...

**Comment by warlordjones** [comment]
I will take a look at it myself at some point though, because decebal isn't really here atm.

**Comment by decebaldecebal** [comment]
I was thinking of making it work like this, but it will be quite a lot of work.I will have to re-write part of the system.
You can however place the lightning rod first, then set to extraction, then place something else and that should work...

**Comment by warlordjones** [comment]
Ah, yes, that will work in the meantime. Its a quirky system, but cool when you get used to it.

**Comment by WolfieWaffle** [comment]
You could maybe look into Thermal Expansions reconfigureable sides, I don't know if it's open source though.

**Comment by decebaldecebal** [comment]
Sided selection was not added, but it is not needed anymore since Wires can now accept power.
Fixed in 10be635ba6f2e46052fed088b5367d445c0d354f

**Comment by warlordjones** [comment]
That'll work :+1:
