### ISSUE TITLE
Modelled Blocks have Missing 'Breaking' Textures

### ISSUE THREAD

**Issue by Jamm6gamer** [BrassGoggledCoders/SteamCraft2#188]
The copper cables and other cables teleport you. 
 Most of the modeled blocks if breaked make a missing block texture. 
 The armor editor the top hat the google module the PDA and the spawns have missing textures.

**Comment by warlordjones** [comment]
1. More information please
2. Highly minor bug, not worth the effort of fixing it atm in my opinion
3.  All except the armour editor it that list are WIP creative-only items...the armor editor is my bad, its not a broken texture, I just haven't got round to making it one yet.

**Comment by Jamm6gamer** [comment]
1. i,m don't are english native 
2. i know :/
3 ok thanks for help some :/

**Comment by WolfieWaffle** [comment]
2. I think that it is worth fixing, It doesn't seem like it would be the most hard thing to do. I don't really know how to do advanced modding, but this thread makes it look like you just have to assign an icon for the block: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/1431587-solved-missing-texture-particles

**Comment by warlordjones** [comment]
I am now going to be fixing this, as you say, its a lot easier to fix than I thought.

**Comment by WolfieWaffle** [comment]
Nice! I hope it works.

**Comment by warlordjones** [comment]
Should all now be working...I may have missed some though
