### ISSUE TITLE
B3.5c Issues

### ISSUE THREAD

**Issue by DraaxLP** [BrassGoggledCoders/SteamCraft2#189]
So I have noticed while playing this version in a custom pack that I have been working on and I have ran across a few issues. 

1. There doesn't seem to be a recipe for the drill base in NEI. 

2. The drills don't really seem to work on anything but stone, dirt, gravel, cobble.

3. The Steam-Powered Jetpack seems to drain steam constantly. Flying or not. 

These issues may be intended but I haven't came across anything that says so. I am really enjoying this mod and can't wait to see where you guys take it.

**Comment by warlordjones** [comment]
Investigating :)

**Comment by DraaxLP** [comment]
If required I am more than willing to put up a video showing the actions described in the original post.

**Comment by warlordjones** [comment]
Nope, should be fine, think I know how to fix them too :P

**Comment by warlordjones** [comment]
Fixed. Cheers for the report.

**Comment by DraaxLP** [comment]
Glad I could help.
