### ISSUE TITLE
Crash when using copper wire

### ISSUE THREAD

**Issue by ClockwerkKaiser** [BrassGoggledCoders/SteamCraft2#190]
I ran into a crash when playing with copper wire, lightning rods, and battery banks. 

I was seeing if attaching the lightning rods to the battery bank via copper wire would work. The game crashed as I went to place the any wire after the 3rd. I also attempted to place the wire on a seperate bank after, and the crash happened again. 

Here is a pastebin of the crash: http://pastebin.com/W3KVuYjP

And if you want to see it in video form (within the next 14 days) here is a link to that http://www.twitch.tv/clockwerkkaiser/b/623584294?t=4h52m20s

**Comment by decebaldecebal** [comment]
The crash seems to happen here:
https://github.com/BrassGoggledCoders/SteamCraft2/blob/master/src/main/java/steamcraft/common/blocks/machines/BlockCopperWire.java#L131

It seems to be related to some tile entity from railcraft that is replacing the tile entity of the wire, which should not happen.

An easy fix would be to actually check if the tile is and instance of TileCopperWire and only then cast it.

**Comment by warlordjones** [comment]
Bah, thats fake air blocks for you. You can disable them in the RC config until I can fix this.

**Comment by warlordjones** [comment]
Fixed our side, and PR submitted to RC (CovertJaguar/Railcraft#32)

**Comment by mallrat208** [comment]
I think that the copper pipes also need a fix for this.

https://github.com/BrassGoggledCoders/SteamCraft2/blob/28e275cc060db3a44e18c72db8c43c63bea4a846/src/main/java/steamcraft/common/blocks/machines/BlockCopperPipe.java#L115

**Comment by warlordjones** [comment]
Indeed
