### ISSUE TITLE
Bug with Boilers and Steam

### ISSUE THREAD

**Issue by ClockwerkKaiser** [BrassGoggledCoders/SteamCraft2#191]
I found a bug, I'm providing an image guide as well. 

I was playing around with the Nuclear-Fired boilers in creative. I set up two boilers on one pipe system running to two Steam-Powered Turbines.
![Boiler setup when testing](http://i.imgur.com/pwT5K6O.png)

This boiler is working perfectly.
![Boiler 1 is good](http://i.imgur.com/AanvPfD.png)

As is the other boiler. 
![Boiler 2 is also good](http://i.imgur.com/uqG5OGM.png)

After a few minutes, I realized that a single boiler could power both turbines just fine. So, I broke the leftmost boiler (which was full of steam BTW) and the unneeded pipes (also full of steam).
![Realized I only needed 1 boiler to power both turbines](http://i.imgur.com/JFUEGCR.png)

This is the result. The remaining boiler is glitched out, will no longer create steam, nor will it allow any more steam to be pushed to the turbines. The whole system locked up til I broke and replaced the glitched boiler. 
![This is what happens when you break a full boiler in a two boiler system](http://i.imgur.com/cJdWFEo.png)

I didn't get a screenshot of the battery bank showing that it was no longer recieveing electricity. But trust me on this, the turbines completely stopped during the glitch as well.

So yeah. Bugs! yay! :D

**Comment by warlordjones** [comment]
Woah wat. That - sounds odd. Investigating. Cheers for the report :D

**Comment by ClockwerkKaiser** [comment]
Awesome! 

I thought I'd try to replicate it to see if it was a one time bug. Here is the result. 

The same two-boiler setup
![Setup](http://i.imgur.com/YaxKL27.png)

Looking good! 
![All good!](http://i.imgur.com/25qhu0P.png)

After breaking the 2nd full boiler/extra full pipes.
![After the break](http://i.imgur.com/2A3Fkou.png)

This time, however, the amount of steam fell at a steady pace until it stabilized at 10000. The system didn't freeze during this test. 

Random thought: You know what would be a good punishment for someone like me who destroys boilers /pipes which are full of steam? A nice BOOM! :P xD

**Comment by warlordjones** [comment]
Hrm, yeah, I'm having trouble reproducing that.

Boom you say? Explosion doesn't seem quite right, its only steam, but, hmm, steam cloud sounds painful

**Comment by ClockwerkKaiser** [comment]
Ooh I like that even better! :D

**Comment by decebaldecebal** [comment]
This might be a problem with the pipes themselves not updating, not the boiler.If you replace the pipe that extracts from the boiler I think everything should come back to normal...

**Comment by mallrat208** [comment]
Peanut Gallery:

I've had a similar bug with Brewcraft's Barrels showing a massive amount of fluid stored in them. It's only occurred when using Forge 1291 or higher as they changed the default behaviour of FluidTanks saving/reading NBT checking for empty.

**Comment by ClockwerkKaiser** [comment]
That could very well be the issue. I am using Forge 1291 as a couple mods I play with now require it :/

**Comment by warlordjones** [comment]
Aha, I shall investigate further, ty for the extra info

**Comment by warlordjones** [comment]
¯\_(ツ)_/¯
