### ISSUE TITLE
Copper Pipes won't insert into a Brewcraft Brewery

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#192]
Forge: 1286
SteamCraft2:  1.7.10-B3.6
Boilerplate: 1.7.10-3.0.6
BrewCraft: 1.7.10-1.2.3
RedGearCore: 1.7.10-2.2.1

So, I'm maybe 70% sure this goes here, if not feel free to disregard...

The Brewery in BrewCraft has two tanks. One allows only for the insertion of fluids. The other only allows for extraction. When using Copper Pipes, I'm unable to pump water into input tank. I can however use the Copper Pipe to extract a fluid from the output tank. 

I have been able to pump water into the Brewery's input tank using other mods (Railcraft, BuildCraft, and ExtraUtilities) which is why I think this may need to go here.

**Comment by warlordjones** [comment]
Hrm. I'll investigate

**Comment by decebaldecebal** [comment]
All the bugs related to pipes should be fixed.
