### ISSUE TITLE
[Suggestion] Regarding Brass Trees

### ISSUE THREAD

**Issue by ClockwerkKaiser** [BrassGoggledCoders/SteamCraft2#193]
In the past few days of playing, I realized that Brass tress spawn very often (even when set to "1" in the config). This alone wouldn't be a huge issue if not for the fact that Pickaxes which are only supposed to break up to Copper-level ores can also break the Brass leaves. After smelting and combining the nuggets, I can easily get 1 to 2 stacks of Brass ingots off a single tree. 

So, my suggestions are

1) Lower the amount of brass tree generation (or tweak the configs so the players can do it themselves)

2a) Raise the mining level of the Brass leaves
OR
2b) Make it so the brass leaves break and only have a chance to drop a brass nugget/ingot (nuggets more common). Then make the brass leaves only gatherable with silk touch picks. 

Either one of those would be fantastic for players/modpack authors who don't want to be able to (easily) get a bunch of brass before they should even have iron.

**Comment by warlordjones** [comment]
I think I will implement all of them. I need to look at generation chance, it doesn't work quite right

**Comment by ClockwerkKaiser** [comment]
Sounds good! 

Yeah, I've been finding myself searching for the trees at the beginning of playthroughs, because it lets me completely skip over the copper/iron tiers using only a flint pick (tinkers+iguana's).

I was thinking of disabling them temporarily in the overworld... but I do love the way they look. I'll try to figure out another way to raise their harvest level til they're updated. 

I think iguana's might have a way for me to do it. 

But yeah, Keep up the great work!

**Comment by warlordjones** [comment]
Closing this for now, the generation chance is a more general issue
