### ISSUE TITLE
Crash regarding the Thaumic Monocle

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#194]
Updated to Beta 4, get the following crash that seems to mention something about the Thaumic Monocle. I do not have Thaumcraft installed: http://pastebin.com/eKjeGhiX

**Comment by mallrat208** [comment]
Looks like there's a tyop in ItemBrassArmor

On line 49 has value of "Railcraft" for the modid. It should be
"Thaumcraft".

**Comment by warlordjones** [comment]
Whoops, copypaste fail >.< :P
