### ISSUE TITLE
Cast Iron Railing: Recipe should yield additional items.

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#198]
This is less a bug and more of an opinion.

For what they are the Cast Iron Railings are pretty much analogous to Iron Bars. They're made the same way from what is just a slightly more processed iron. The difference is you get a single cast iron railing vs 16 Iron Bars, the Cast Iron Railing should be about the same given the cost.

**Comment by warlordjones** [comment]
Hrm, I thought I changed this - oh, no, that was fence. No, I agree completely, my bad.
