### ISSUE TITLE
Battery Bank: Comparator Output Override

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#200]
Alright, so I was playing around a bit with the Battery and noticed it does support using a comparator to get a signal off of it. It however doesn't seem to function as I would have expected. 

```java
	public int getComparatorInputOverride(World world, int par2, int par3, int par4, int par5)
	{
		TileBattery tile = (TileBattery) world.getTileEntity(par2, par3, par4);
		return tile.buffer.getEnergyStored() / 1000;
	}
```

Unless I'm mistaken that will only ever report the first 5000 energy that the block itself stores with out any leyde...crystal jars.. divided by 1000. So it'll output 0~5 and no more.

It would seem to me that it would a bit more useful it actually queried the battery's total energy stored including jars as a percentage and then multiplied that out by 15, rounded as needed to get a nice number that works for the standard 0~15 you normally get on redstone strength.

**Comment by warlordjones** [comment]
Sounds good to me.
