### ISSUE TITLE
Polished Oak Planks: Any chance for a less time consuming recipe?

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#201]
The Recipe for Polished Oak Planks call for 1 Water Bucket and 1 Oak Plank to make 1 Polished Oak Plank. 

It's definitely not a hard recipe nor is it expensive especially considering in near all packs water is an infinite and readily available resource. The recipe itself is rather time consuming however since you need to fill a water bucket for every single plank you want to craft. 

It'd be a bit easier if you used say either 4 Planks and a bucket to make 4 Polished Planks or a full 8 Planks and a Bucket to make 8 Polished Planks.

Alternatively if there were some sort of wood polish or oil to use that'd be better ;p

**Comment by warlordjones** [comment]
Its a temporary recipe until I think of a better one - probably including whale oil, which is NYI (not yet implemented)
