### ISSUE TITLE
Cast Iron Fence: Cast Iron Fences may be a bit Expensive.

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#202]
The recipe for Cast Iron Fences is pretty analogous to the recipe for a vanilla Fence. 6 Sticks which yields 2 Fences. The problem is that each Cast Iron Rod used takes 2 Cast Iron Ingots. So you're looking at 6 cast Iron Ingots for a single cast iron fence.

While I understand that It's not a great idea to make a mod limited by what others have already done, the closest modded fence to the Cast Iron Fence that I can think of is the Railcraft Posts which cost you 7 Iron Ingots to get 16 Metal Posts. Granted that is done via the Rolling Machine and not as a manual recipe but it's still a rather large disparity in cost.

**Comment by warlordjones** [comment]
I thought I edited this already. Can't remember what I changed. Suggestions for a number of fences to output?
