### ISSUE TITLE
Hammer Crash

### ISSUE THREAD

**Issue by Chocohead** [BrassGoggledCoders/SteamCraft2#204]
I tried crafting the hammer, and got this crash: http://pastebin.com/P2ZLfcqB Upon world reload the items were gone, but I didn't get a hammer :(

**Comment by warlordjones** [comment]
Known issue, going to be fixed in Beta4.3 which should be out in a few hours. I used scala.Arrays.asList not java.Arrays.asList

Feel free to call me a derp :P

**Comment by warlordjones** [comment]
I'll close this, already fixed in dev

**Comment by Chocohead** [comment]
I guessed as much from https://github.com/BrassGoggledCoders/SteamCraft2/commit/37cc74e71676b646bbe09aad8e9bf9c310f0a998
