### ISSUE TITLE
Bloomery Recipe only uses 1 coal, not four.

### ISSUE THREAD

**Issue by Chocohead** [BrassGoggledCoders/SteamCraft2#205]
The bloomery allows you to make steel out of iron and coal, but although it takes 1 iron ingot and 1 coal, it still needs 4 coal in the input slot, despite only using 1.

**Comment by warlordjones** [comment]
Hm. Its intended to use 4 coal.

**Comment by warlordjones** [comment]
After actually testing this, I can't reproduce...
