### ISSUE TITLE
Raygun strange fire creation

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#209]
When you fire the raygun, it creates fire, but the fire is not even. Sometimes it creates lines of fire, always aligned to the same axis. It's a bit hard to notice at first, but just try making a path of fire with the raygun on a superflat world and you should see a pattern:
![2015-05-26_19 57 20](https://cloud.githubusercontent.com/assets/8770485/7827194/77cbf258-03e1-11e5-9e1a-c41e16282a41.png)

**Comment by warlordjones** [comment]
Yeah, I need to look at the code being used to decide where to put fire...

**Comment by WolfieWaffle** [comment]
OK, I just thought it was a bit strange and wasn't aware if you knew about it so I put it here.

**Comment by warlordjones** [comment]
Closing, as not exactly a bug
