### ISSUE TITLE
Metal blocks are not "iron" material

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#212]
I don't know if this has been fixed since the last update, but in my version it appears that the metal blocks are of the material "rock" or some other material. This is minor, but if might cause bugs with certain mods, like iguanatweaks, that use the material of blocks. It's a really simple fix, but I think it's one of those things like making tools render in 3d or making sure a model has a block break texture that make the mod more complete.

**Comment by warlordjones** [comment]
No need to justify why I should fix bugs :P Thanks for the report, I'll fix this next dev session.

**Comment by warlordjones** [comment]
Hrm, they are iron material AFAIK.

**Comment by warlordjones** [comment]
Yup, definitely seems to be Material.iron
