### ISSUE TITLE
Incomplete texture models and block break textures

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#216]
You probably already know about these, and I know I'm making a lot of issues on GitHub, but I'm just trying to find all the bugs and make them official :P

Either way, the battery bank does not have a block break texture and these blocks have a strange model:

![2015-06-13_14 44 23](https://cloud.githubusercontent.com/assets/8770485/8145958/a0f9f29e-11db-11e5-9a1a-ed4f0a845a36.png)

**Comment by warlordjones** [comment]
Don't worry about making too many issues, I can't fix what I don't notice :P

Yeah, all those models are WIP. Battery Bank tex is an oversight, will fix soon, and I also need to remodel it a bit.

**Comment by WolfieWaffle** [comment]
OK, cool. Related to the battery bank, the capacitor does not seem to allow items inserted into it. I don't know for sure though, maybe do more testing on it.

**Comment by warlordjones** [comment]
Ah, I probably forgot to do that too...
