### ISSUE TITLE
Time bomb... I don't even know inventory glitch

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#218]
When you open the time bomb this happens... it should be pretty obvious what the problem is, but it also duplicates your hotbar, I didn't do that.

![2015-06-13_14 46 48](https://cloud.githubusercontent.com/assets/8770485/8145962/fecb47ce-11db-11e5-8cea-c6470752386e.png)

**Comment by warlordjones** [comment]
Gosh, that's another issue I thought I'd fixed already. Hang on, what version are you using?

**Comment by WolfieWaffle** [comment]
The latest one on curseforge, B4-4

**Comment by warlordjones** [comment]
Ah, ok, looks like I failed at fixing it then. Will look at it.
