### ISSUE TITLE
Life vest module weird behavour

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#219]
When I use the life vest and go into the water, it makes me bounce up and down like crazy. I don't really know if it's a bug, but it's pretty annoying when it's happening to you. Maybe look into TConstruct travelers boots, they allow you to walk on water with a lily pad upgrade that works pretty well, maybe see how they did that.

**Comment by MrIbby** [comment]
Looking at [the localization file](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L977) and [the code](https://github.com/SlimeKnights/TinkersConstruct/blob/a7405a3d10318bb5c486ec75fb62897a8149d1a6/src/main/java/tconstruct/armor/items/TravelGear.java#L39), it seems Traveller's Vest has called "Swift Swim"

**Comment by warlordjones** [comment]
Hrm, its not intended to make you walk on water...and it is intended to make you bob a little, how much is 'like crazy'?

**Comment by WolfieWaffle** [comment]
Like i'm make of rubber or something. I know it's not supposed to make you walk on water, but maybe the not-sinking effect could be useful. It's basically more like bouncing than bobbing, but I don't know any way to specifically quantify it.

**Comment by warlordjones** [comment]
Ok, right, I'll look into it.
