### ISSUE TITLE
Uranium balancing

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#230]
Uranium seems to be very rare, so I imagine that it's very valuable. But when I tried using it in the uranium powered steam boiler, it produced only a very small amount of steam. If it is going to be so valuable, I think it should at least produce a lot of steam (aka lasting longer in the boiler). I don't know exactly how much, but at least enough to make it worth mining. Maybe even adding a config option for a uranium fuel amount multiplier. This would be helpful for modpack makers (like me :P) and would make uranium a more viable fuel source.

You could even make uranium fuel more complex and powerful but dangerous with reactors and nuclear waste and explosions/overheating, but that's a major change. For now I'm just suggesting that uranium be more useful.

**Comment by warlordjones** [comment]
I'm not sure I want to do much more with uranium, as I've decided it doesn't really fit that well into the mod into is current form. I'll increase the length it lasts though. I'm also considering how to retheme it a little to fit better.

**Comment by WolfieWaffle** [comment]
Well, I'm being captain obvious here, but id would need to be more steampunk-y. It would need to be used for steam creation, not direct power generation, but that's already how it is. Maybe you could combine it with phosphorus to make a radioactive light source, or glow paint you could put on walls or something. It would be really cool if it could overheat and explode, and would need water to cool it. It would be more complicated to make, obviously, but explosions because of overheating seem like steampunk to me. Maybe you could make weapons with it, which could be related to the nuclear siren. I think anything in this mod that relates to uranium would probably have to do with it's heat generation. Using it to create steam in a big boiler that needs to be cooled down is steampunk-y, but a fururistic reactor with fuel cells is not.

I don't know, I'm just peculating and trying to find ideas :P

**Comment by warlordjones** [comment]
Yep, sounds like I could take it in a steampunk direction...I'll keep thinking :P
