### ISSUE TITLE
Mod compatibility issue?/Enhancement? with slate (all 3 of them)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#232]
Slate does not work with the Builders Wand (extra utils) nor can I get a chisel to work (Chisel2 and TCon chisel).

**Comment by warlordjones** [comment]
Not sure why the builder's wand doesn't work, but its not intended to work with the chisels. I may add that though

**Comment by TheQuadShot** [comment]
I also can't make them into stairs, that would be really nice, so they will match my floors/walls

**Comment by warlordjones** [comment]
I'll add stairs, that should be quite a quick thing to do

**Comment by TheQuadShot** [comment]
Cool! Thanks!!
