### ISSUE TITLE
Missing texture for Steampunk's Handbook in NEI

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#233]
I'm running v. -B4.4

![2015-06-19_12 39 53](https://cloud.githubusercontent.com/assets/11265900/8262580/25dad5d6-1688-11e5-93d3-387a1e462456.png)

**Comment by warlordjones** [comment]
Item is heavily work in progress, and has no recipe. As such, there is no problem with it not having a texture.

**Comment by TheQuadShot** [comment]
Sorry, didn't know it was a WIP (I don't file WIP's unless asked)

**Comment by warlordjones** [comment]
No worries :)

**Comment by WolfieWaffle** [comment]
I could try making a texture for it, books are one of my favorite textures to make.

**Comment by warlordjones** [comment]
If you would

**Comment by WolfieWaffle** [comment]
How about this: 
![book_brass](https://cloud.githubusercontent.com/assets/8770485/8264381/841bc320-16a2-11e5-8b68-7a523875da4c.png)

**Comment by warlordjones** [comment]
I like it!

**Comment by WolfieWaffle** [comment]
tnx :)

**Comment by TheQuadShot** [comment]
I vote yes :-)

**Comment by MrIbby** [comment]
We've found ourselves a new texturer :P @WolfieWaffle

**Comment by warlordjones** [comment]
We have indeed @MrIbby , he's been emailing me a load of textures, check out the new obisidian armour texture for example
