### ISSUE TITLE
Tesla coil textures

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#234]
Similar to the armor editor thing. This should explain it:

![2015-06-19_15 50 34](https://cloud.githubusercontent.com/assets/8770485/8264388/a87ba136-16a2-11e5-803a-b27b83258f9a.png)

**Comment by warlordjones** [comment]
Oops...

**Comment by warlordjones** [comment]
I seem to have fixed this previously, and not closed the issue.
