### ISSUE TITLE
Crash when entering Deeps Portal

### ISSUE THREAD

**Issue by Majestyc2k1** [BrassGoggledCoders/SteamCraft2#235]
Received this crash when I entered the Deeps Portal for the first time: http://pastebin.com/Ck9nYPcQ

**Comment by warlordjones** [comment]
Interesting...are you on superflat by any chance? (had reports of that
before)

Arona
[+] You're welcome to add me to your address book
<https://ws.writethat.name/kwaga-bin/titan/WEB/me.pl/2040834221374130777/i>

**Comment by warlordjones** [comment]
Ouch! Please pastebin your crashes...spoiler tags don't work here. I edited the post to move it to pastebin.

Anyway, onto the issue. First question: are you on superflat (for some unfathomable reason)?

**Comment by Majestyc2k1** [comment]
No, a regular generated Survival world.

**Comment by warlordjones** [comment]
Damn. I'll investigate further....

**Comment by warlordjones** [comment]
Dupe of #282 it would seem
