### ISSUE TITLE
Polished Oak Planks are too easy to break

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#236]
I can break them with one hit with open hand. Nice in some cases, but I'm staggering them with the vertical and horizontal, and I end up breaking 3 or 4 at one time. I'm running the 4.4 build

**Comment by TheQuadShot** [comment]
All 4 of the sirens also break with a single left click with open hand

**Comment by warlordjones** [comment]
Whoops, minor oversight their, their hardness is zero. Easy fix.

**Comment by warlordjones** [comment]
Fixed in latest build of **Boilerplate**
