### ISSUE TITLE
Breaking vertical polished planks drops polished (horizontal) planks

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#237]
I'm running build B4.4

**Comment by warlordjones** [comment]
Oh wow, I do make a lot of these mistakes...

**Comment by TheQuadShot** [comment]
btw, the polished panel does the same thing. Aside from that

WoW! this looks GREAT!! 
![2015-06-21_23 38 17](https://cloud.githubusercontent.com/assets/11265900/8277940/19d6a526-187c-11e5-8e4a-a2496ee17a02.png)

**Comment by WolfieWaffle** [comment]
Wow, that really does!

**Comment by warlordjones** [comment]
Well, that makes 2 textures I've made that aren't terrible :P

**Comment by warlordjones** [comment]
Fixed in Boilerplate/c20a1fa139490a2fcadb658f511641a36f95a8fc
