### ISSUE TITLE
Bronze powder = Tinkers Alloy?

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#238]
I'm not sure about this one, I'm sorry If I got it wrong. I create powders in a Sag Mill, and combine them to bronze powder in a crafting table. I then drop them into the Ender's alloy smelter, in furnace only mode and get Tinkers Alloy (which is "normally" made in an MFR induction smelter)  back, I can create bronze plates with it. I get bronze ingots if I drop them into a vanilla furnace. I guess my point is that it's a little confusing, I'm expecting bronze ingots since the only way to make bronze (in this instance) is mixing the powders in a crafting table and when I got the tinkers I panicked a bit. So I'm not sure if Ender's (or some other mod, like MFR) "stepped" on it, ignored it, or if it's not getting "sent/handed" the correct info... Over all it doesn't really matter since as far as I can tell it's all good.  Does any of that make sense?

**Comment by warlordjones** [comment]
Tinker's alloy = bronze AFAIK, TE just names it oddly I believe

**Comment by WolfieWaffle** [comment]
Though IIRC, some of the SC2 dust ratios for alloying are different from other mods. For example bronze or brass, one of those two, requires 3 copper and one tin in most cases, but only 2 copper in sc2. I might jut be remembering incorrectly though.

**Comment by warlordjones** [comment]
I'll look at that. I do know that the metals required should be accurate at least, amounts are fairly subjective. Balance is not something I'm worried about in beta, especially not against other mods. Also, fun > balance IMO.

**Comment by WolfieWaffle** [comment]
OK, as a modpack maker, (kinda) I'm always thinking about other mods. For me, balance = fun :P. Well, balance and lasers. And jetpacks.

**Comment by warlordjones** [comment]
Lasers and jetpacks <3

Also, I've nothing against minetweaker :P

**Comment by WolfieWaffle** [comment]
Minetweaker? I don't remember mentioning it, but yeah, I could use that for now.

**Comment by TheQuadShot** [comment]
I noticed this is tagged "need more info" Is there something I need to or can do to help?

**Comment by warlordjones** [comment]
@WolfieWaffle You didn't mention it, just suggesting you could use it :)

@TheQuadShot I tagged that because I'm not entirely sure I answered your question, did I? XD

**Comment by TheQuadShot** [comment]
Yes, and I understand it's a very low priority issue. Just wondering if there's something more I can do, since I have time to spare.

**Comment by TheQuadShot** [comment]
I'm also trying to "wrap my head" around exactly how things work, since I've had some "major" miss-understanding of a few things and I'm trying to help as much as possible. I love these mods and want them to progress as fast as possible ;-)

**Comment by WolfieWaffle** [comment]
I think one of the best ways to help is just to find and report bugs, at
least in my experience. I've reported a lot of bugs, both in this mod and
others, that have gotten fixed pretty quickly. If you can't make mods very
well (like me) I think bug reporting is a way to help.

**Comment by warlordjones** [comment]
Yep, bug reporting is definitely a way to help - I don't get to play with the mod much, too busy making/fixing it, thus I don't find the bugs.

Documenting it could also be reeeeeeeeeally helpful. Do that over here: http://ftb.gamepedia.com/Steamcraft2 :D

**Comment by warlordjones** [comment]
Wait, what exactly is the issue you are experiencing? It isn't clear from the OP...

**Comment by TheQuadShot** [comment]
it's basically this: 
Bronze = 2 copper dust + 1 tin dust
Tinkers Alloy = 3 copper dust + 1 tin dust

If I drop the bronze dust into the ender alloy smelter (in furnace only mode) I get tinkers alloy.
If I drop the bronze dust into a vanilla furnace I get bronze.
Does that help?

**Comment by warlordjones** [comment]
Yeah, that's because Tinker's alloy = bronze in the ore dictionary. You can't convert the bronze back to copper/tin so it shouldn't be a gamebreaking balance issue. I may increase the copper usage to 3 though.

**Comment by TheQuadShot** [comment]
Yes, I understand, and I'm trying to understand a few things. For instance, I have Sulfur, but's it's from some other mod (not sure cause waila doesn't work on my machine due to a bug) but when I try to make sulfuric acid, it doesn't work, so who "owns" the issue? Hopefully this is starting to make more sense :)

**Comment by warlordjones** [comment]
Gah, that's probably my bad, I've made a bit of a mess of sulphur registrations, I'm not sure which one is the standard. Doesn't help that I'm inconsistent in spelling sulphur...

**Comment by decebaldecebal** [comment]
The title issue is fixed in 01159adf8346f6880d4a53c1979b3ef86e11c90e
