### ISSUE TITLE
Obsidian Armor fire immunity doesn't work

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#239]
I mentioned a while ago that obsidian armor should probably not use potion effects. I saw somewhere that it was changed, but there are still some issues:

1. Obsidian armor still gives you slowness potion effect, rather than using playerAttributes to make it heavy.

2. The fire resistance does not work.

I am using the jenkins build 16.

**Comment by warlordjones** [comment]
I've not yet switched the slowness, only the fire resistance...I'll investigate it being broken.

**Comment by decebaldecebal** [comment]
Fire immunity can't be easily coded because you can change the player resistance to fire, but you have to change it back when the armor is not worn anymore, which is just more complicated than just using a potion effect.

**Comment by warlordjones** [comment]
You can just extinguish them if they are on fire, no?

**Comment by warlordjones** [comment]
Dirty, but it works.

**Comment by warlordjones** [comment]
Or should :P

**Comment by decebaldecebal** [comment]
Yes, but they get extinguished only when they come out of the fire, but they still get damaged while they are in fire.

**Comment by warlordjones** [comment]
Hrm. Ok.

**Comment by WolfieWaffle** [comment]
Wait, so is this still open or did someone fix it? The first part seems
like it got fixed, but the conversation afterwards seems like it's not.

**Comment by warlordjones** [comment]
Its all working, back to using a potion effect for fire resistance tho

**Comment by WolfieWaffle** [comment]
Ok, that's fine. As long as it doesn't override existing fire resistance effects you have on. Also, are the particles ambient?

**Comment by warlordjones** [comment]
Should be

**Comment by warlordjones** [comment]
Oooh, it might override existing fire resist though. Not much I can really do about that...

**Comment by WolfieWaffle** [comment]
Maybe you could only apply it if you don't already have fire resistance?

**Comment by MrIbby** [comment]
I'm pretty sure it doesn't affect existing fire resistance. If the current effect is longer, than it doesn't change.
