### ISSUE TITLE
Wire shouldn't connect to side of steam turbine

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#240]
If I can only get power out of the top, then it shouldn't connect to the side.
![2015-06-20_15 53 00](https://cloud.githubusercontent.com/assets/11265900/8269586/bd260abe-1764-11e5-8f45-1a81ffc014bf.png)

**Comment by warlordjones** [comment]
Well, top and bottom now, but yes. Will change.
