### ISSUE TITLE
Right click on steam turbine with copper pipe = crash to launcher

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#241]
http://pastebin.com/fWupn2Xx

**Comment by warlordjones** [comment]
D: That's no fun...investigating..

**Comment by TheQuadShot** [comment]
Sorry I should give you a little more to go on, I had a wire coming off the top going to the top of a charger, I also have a pipe connected to the side of the turbine (from steam supply). The charger isn't showing any power "feeding" into it, So I tried to right click on turbine in hopes to see some kind if ui to see if it's actually making power...

**Comment by warlordjones** [comment]
You gave me enough info to reproduce the crash, "investigating" is just my go to statement for "please hold while I try and fix this". There's no UI for the turbine yet - have you set the wire to extract mode by right clicking it with a spanner?

**Comment by TheQuadShot** [comment]
I didn't know that was a thing... I just noticed it on the pipe, but now's it working :)

**Comment by TheQuadShot** [comment]
I think this is fixed, it's not repro-ing in the latest build, Jenkins buld 27, and 11 for boilerplate
Y'all been cranking on this stuff! just plowing through the bug list! Kudo's!! and Thanks for all your hard work!!

**Comment by decebaldecebal** [comment]
Yep, it is fixed in d1159096aed1fc61e83a4f941363c15134f71a1f

**Comment by warlordjones** [comment]
Yep, I've been doing a bit of work, but decebal's been doing the heavy lifting :D
