### ISSUE TITLE
Copper pipe should have glass in recipe, since I can see the steam in it.

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#242]

**Comment by warlordjones** [comment]
Sure

**Comment by TheQuadShot** [comment]
I know this is an enhancement, but I can't get it tagged as such.. sorry about that.

**Comment by warlordjones** [comment]
Yep, Github only allows people with write access to the repo to tag issues for some reason. Don't get it - you should be able to tag your own issues IMO...
