### ISSUE TITLE
Tool Tips for wires and pipes so users know to use spanner/wrench

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#243]
enhancement :)

**Comment by warlordjones** [comment]
These should be already implemented, I may have broken them though...guess this gets bug then..

**Comment by TheQuadShot** [comment]
Ohhh, It would also be nice to allow connect/no connect on parallel pipes and wires

**Comment by warlordjones** [comment]
I'd like to implement that at some point.

**Comment by warlordjones** [comment]
Nope, I didn't break the tooltips, this is already working :)
