### ISSUE TITLE
[Enhancement] Test issue

### ISSUE THREAD

**Issue by warlordjones** [BrassGoggledCoders/SteamCraft2#244]

**Comment by warlordjones** [comment]
Aha! It works!!

**Comment by warlordjones** [comment]
Right, hopefully this goes to plan. 

@WolfieWaffle, @TheQuadShot and others who often report issues, adding [Feature] or similar to the title of you issue should now mark it for labelling by the bot. This won't happen immediately, the task only runs every 15 minutes, and is currently locally hosted on my machine, so may not happen at all :P

**Comment by TheQuadShot** [comment]
Do I put square brackets around the word (tag) I want?

**Comment by warlordjones** [comment]
Yep

**Comment by WolfieWaffle** [comment]
Cool, it never made sense to me that you couldn't add tags to your own issue.

**Comment by warlordjones** [comment]
Exactly. Guess this will workaround that though
