### ISSUE TITLE
[crash] clicking on obsidian drill in NEI (for recipe) = crash to launcher (related to #245?)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#246]
http://pastebin.com/giV2aexN

**Comment by warlordjones** [comment]
I thought I fixed this in the latest dev build...anyway, I've got to sleep now (It's nearly 2am here!!) so I'll look at all these issues in the morning. Feel free to keep opening more :P

**Comment by TheQuadShot** [comment]
I'll run dev builds, I'm a "retired" QA Manager/Software design engineer in test (I don't know java, but I can figure some of it out), so running "dog food" doesn't bother me ;-)

**Comment by TheQuadShot** [comment]
fyi This is happening on all of the electric drills

**Comment by warlordjones** [comment]
Can you confirm if this is happening in jenkins build 16? http://jenkins.k-4u.nl/view/BrassGoggledCoders/job/SteamCraft%202/

**Comment by TheQuadShot** [comment]
Works Great! no bad things happen, is this build ok to keep running and testing? (I promise to provide correct build number)

**Comment by warlordjones** [comment]
Yep, its usually best to test on the latest build :)
