### ISSUE TITLE
Steam stops rendering in pipes after re-log

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#247]
http://imgur.com/ePjXN2e

**Comment by TheQuadShot** [comment]
what does the wat label mean? should I have use it?

**Comment by warlordjones** [comment]
'wat' is just a "this is odd" label, don't worry.

**Comment by WolfieWaffle** [comment]
wat is like "what?" but more... fun. I use wat as well.
