### ISSUE TITLE
Pocket watch show's a "weird" time

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#250]
This is most likely me misunderstanding how time really works in MC. 
I have gamerule doDaylightCycle false and the clock shows a 7 digit number that continues to increment. 
http://imgur.com/6H2vt5j
What I was expecting was that time would be about 6000, since when I did "stop the clock" on MC, I did a /time set 6000(noon), then I set the gamerule.
I would agree that this is not normal, but I do this when I'm testing things and I don't want to be bothered by mobs or lighting issues.

**Comment by warlordjones** [comment]
I think I'm getting the MC time wrong, I'll have to look into that...
