### ISSUE TITLE
Ray Gun Using Huge Amounts of Energy

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#251]
Try using the ray gun on the ground on superflat. It works fine. Now try using on a jungle tree. It blows through energy a ton. I don't exactly know what more info I can provide, but I imagine that when the energy usage was downscaled, someone forgot to also downscale the energy usage of certain blocks, in this case wood.

**Comment by warlordjones** [comment]
Possible....

**Comment by decebaldecebal** [comment]
I decreased the energy usage and increased the capacity of the Ray Gun and I think it works perfectly now.It's quite a powerful tool and you can cause some mayhem with it, so I believe it's best to keep it balanced.
Fixed in 66fcf38de7eba330f00f8966675b3f35a6adfd8d

**Comment by warlordjones** [comment]
Looks good from here :D

**Comment by WolfieWaffle** [comment]
pew pew :D

This is probably my favorite thing in the mod. :P

**Comment by warlordjones** [comment]
:+1:
