### ISSUE TITLE
[enhancement] Add a tooltip to diving helmet

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#252]
with just the brass chest piece with aqua lung module I can go under water, it would make more sense if it only worked with the diving helmet on.

**Comment by warlordjones** [comment]
The aqualung module is intended to be a modular version of the diving helmet - also requiring the helmet would mean you couldn't wear the brass helmet too. The diving helmet shouldn't allow you to permanently stay underwater if we are being realistic, but fun > realism.

**Comment by TheQuadShot** [comment]
Oh, I assumed(I know, that's bad) that it was required to use the diving helmet I didn't get any indication that the helmet worked by itself. ie tool tip doesn't mention it, it just shows durability, that I don't equate to "you can breath underwater for this long".

**Comment by warlordjones** [comment]
Yeah, the helmet does the same thing as the aqualung. I'll add a tooltip for it...
