### ISSUE TITLE
Power should distribute to all machines that are wired to the steam turbine

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#253]
I have wire running to a capacitor and a charger in parallel, all of the power is running to the capacitor and the power level in the charger is staying where it was before I added the capacitor. 

http://imgur.com/ePjXN2e
http://imgur.com/hBelzXB
http://imgur.com/cIYevOr

**Comment by warlordjones** [comment]
I *think* that's a fundamental of how the power system works, I"m not sure as I'm not the original author. I"ll look into changing that, no promises though.

**Comment by TheQuadShot** [comment]
Yea, this is kind of incomplete in my testing as well, I would like to have a tool to charge to see if it's just ignoring it because there is no "need" at the charger besides it's internal buffer.

**Comment by WolfieWaffle** [comment]
Just wondering, what power system does sc2 use?

**Comment by warlordjones** [comment]
Homebrew RF based system by @decebaldecebal

**Comment by decebaldecebal** [comment]
The entire system needs a rewrite.This is related to #195 
All further discussions about the power system should go there.
