### ISSUE TITLE
[enhancement] Boiler could use matching icon for steam canister

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#254]
Also the bucket for adding water give's the impression that you can get a bucket of steam (Which to me is VERY funny! I was in the navy, and one of the jokes that was done to noob's was to send them to get a bucket of steam from the number x engine room, this would most likely get them covered in grease that was 90% non-soluble)

**Comment by warlordjones** [comment]
Makes sense, I'll change that.

You'd have to hold the bucket upside down if you wanted it to hold steam, no?

**Comment by WolfieWaffle** [comment]
Or use a bottle. The liquid glowstone bucket from TE is upside down. It
would also be nice if you could just right click with the bucket one the
block and it would fill it, like the railcraft boilers.

**Comment by warlordjones** [comment]
I'll look at implementing that...
