### ISSUE TITLE
Steam drill silk touches some of the dense ore's that it shouldn't (cross-mod compatability)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#255]
The following dense ore's:
Diamond, Lapis, Emerald, Redstone

I'll add to this list if I find any. With the  Dense Ore's mod used so much in mod packs, this should be addressed for the "main" ores at least.

**Comment by warlordjones** [comment]
Hrm, this bug has been encountered by other mods too - I believe Tema sets the drops in an odd way. I'll just edgecase it I suppose..

**Comment by decebaldecebal** [comment]
Should be fixed in a84ac11844795dd70bd975bbb85b680d85dabb18

**Comment by warlordjones** [comment]
I doubt it, the way denseores work is quite special IIRC. I'll reopen to remind myself to investigate.

**Comment by decebaldecebal** [comment]
Well no tool actually spawns any block drops, that is handled by MC itself...So idk why it is a problem...

**Comment by warlordjones** [comment]
Yep, does't make sense to me either, but DenseOres seems to do it. Hrm...guess I'll close it again :P

**Comment by TheQuadShot** [comment]
The reason I brought this up is in one of the mod's I run, it requires the ore blocks to craft an advanced machine. So I'm assuming (again big mistake) that the mod author wants the extra work to craft the machine. (since getting silk touch needs either TCon or the enchantment, both arn't easy to get)
