### ISSUE TITLE
Steam Drill doesn't seem to "respect" enchanments

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#256]
I mined 18 diamond ore blocks with normal steam drill and get 18 diamonds, 
I mined 18 diamond ore blocks with a steam drill with fortune 3 enchantment and receive 18 diamonds.
I mined 18 diamond ore blocks with a Tcon pickax with fortune 3 enchantment and receive 36

**Comment by warlordjones** [comment]
I don't think I ever implemented enchantments yet...therefore I'll tag as enhancement.

**Comment by decebaldecebal** [comment]
It seems like drills have no enchantability.I kind of think that they should remain that way.They should not be a replacement for tools, but rather a convenient way of clearing out terrain very fast, not to be used as a mining tool with enchantments.

**Comment by warlordjones** [comment]
I think I agree actually

**Comment by warlordjones** [comment]
Although...I kind of like drills being upgraded pickaxe/shovel combos. Hrm.

**Comment by WolfieWaffle** [comment]
Me too, maybe "upgrades" would fit with technology more, but I think it's
fine how it is now.

**Comment by MrIbby** [comment]
Is it possible to prevent enchantments? (I would feel rather frustrated to learn that my enchanted drill can't use enchantments.)

**Comment by warlordjones** [comment]
The enchantability is set to 0 afaik, and if this doesn't prevent it then probably not. I"ll look.

**Comment by warlordjones** [comment]
Perhaps upgrades in the future, maybe when I've rewritten, generalised and abstracted the modular systems a bit more.

**Comment by TheQuadShot** [comment]
I would disagree that the drill shouldn't be used as a "normal" tool in mining, there are other way's to clear out terrain quickly, and if that's the only purpose then why would I bother to make one? Am I making any sense?

**Comment by warlordjones** [comment]
I see your point. I still don't think I"ll enable enchants, but I don't think I"ll make it purely a clearing tool. Indeed, that's what the shrinkray is intended to be actually.

**Comment by TheQuadShot** [comment]
I'm ok with not being able to enchant (only kind of), As long as it doesn't cost me xp to find out. The biggest reason I run Tcon and ITT is to get some great tools, and gather resources faster. I don't want to build a quarry until later in the game, when I have a large AE system and lots of automation to go with it. I didn't see a recipe for the shrinkray so I haven't tried it yet (I presumed that it's wip, wip=no recipe).

**Comment by decebaldecebal** [comment]
Well I actually tried enchanting the drills in an enchantment table and I couldn't apply any enchantments...

**Comment by TheQuadShot** [comment]
Oh, I enchant books, then apply them in/on the anvil. I don't risk random enchant's on my tools.

**Comment by MrIbby** [comment]
Hey, we can use `net.minecraftforge.event.AnvilUpdateEvent` to prevent enchantments (while still allowing repairs).

**Comment by warlordjones** [comment]
I already turned off enchants for the electric stuff, there's an easier way.
