### ISSUE TITLE
I can not set time on the time bomb and the ui is a bit "derpy" and it appears to dupe everything on my hotbar.

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#258]
In the image the items on the left are the items in my inventory, it also pushed/moved a steam canister into a personal crafting slot ( the 2x2 grid when you open your inventory). One of the mods I use will allow you to "store" something there provided you have room in your "normal/default" inventory

![2015-06-21_05 23 22](https://cloud.githubusercontent.com/assets/11265900/8271647/44a98d2c-17d7-11e5-8bb0-a81623aec4a4.png)

**Comment by TheQuadShot** [comment]
oops.. Sorry, they are only "ghost" images, if you try to do anything with them, they go away

**Comment by warlordjones** [comment]
I disabled the recipe for the time bomb, it needs a lot more work. There's a heisenbug with the inv code...

**Comment by WolfieWaffle** [comment]
Oh, the always broken time bomb. I think there are at least 3 issues now
relating to it XD

**Comment by warlordjones** [comment]
Yep  XD
