### ISSUE TITLE
Chronometer of Time only sets time to day

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#259]
Shift right clicking sets time to day. It also appears that the ender eyes only get consumed after x number of "uses". ie, if I have 4 eyes in my inventory on the 4th use all of the eyes go away but not until then,

**Comment by warlordjones** [comment]
Hunh. Odd.

**Comment by warlordjones** [comment]
Cannot reproduce either bug. You need to be holding shift when you release RMB for the night setting to work. Ender Eyes seem to be consumed properly too...

**Comment by TheQuadShot** [comment]
hmm, I did try it a dozen times with shift held and the "sneak" button held, I wanted to re-test things with the new build, but I needed to sleep ;-) I'll retest as much as I can and close any that don't repro.
