### ISSUE TITLE
Power will not transfer to charger with item in the charger.(Jenkins build 16)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#261]
The only way to charge the drill is to remove it from the charger and wait for the buffer to fill then drop it into the charger. It also appears that the capacitor holds it's charge and doesn't transfer to anything, I whacked it with wrench and broke the wire and replace it (breaking it looses it's charge).

**Comment by warlordjones** [comment]
>.> Dear me, the power system really is quite borken.

**Comment by TheQuadShot** [comment]
This is only "kind" of working, here's a video of what's happening now (it works for a about 1 minute then stops), it's about a 7 minute vid and I think I cover quite a bit in it.
https://youtu.be/mdQ0arUA6Bg

**Comment by warlordjones** [comment]
Weird...like decebal has said, the system kind of needs a rewrite, and as he is the original author, I'll wait for him to get back to work on this. He should be done with exams in two weeks :)

**Comment by TheQuadShot** [comment]
Yup, Exams come FIRST... darn... ;-)

**Comment by decebaldecebal** [comment]
It's a general problem with wires, related to #195
