### ISSUE TITLE
[minor] Tea plants need increased seed drop

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#263]
Tea plant don't drop enough seeds, so I have to continually go hunting for seeds. If I start with 5 seeds, those plants will only drop about 3 seeds, and those 3 will drop may 1. The only other problem I have is that I can't figure out how to make tea, and there is no recipe for tea cups, are these still wip?
I'm running jenkins build 27, and 11 on boilerplate.

**Comment by warlordjones** [comment]
Ah, that's probably a good plan.

Tea cups should have a recipe, I'll take a look

**Comment by TheQuadShot** [comment]
I noticed the more info needed tag, What do I need to provide/do?

**Comment by warlordjones** [comment]
Nothing, I just need to investigate the tea cup recipe being missing :)

**Comment by TheQuadShot** [comment]
Sorry, it's my CDO (ocd to the rest of the world) ;-)
