### ISSUE TITLE
[minor] Steam boiler seems to stop when capacitor and charger reach 1M rf

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#264]
I took these screen shot's then I tested bug 195, 240, 241,... and a few others, I broke the insulated wire on the turbine and replaced it, the boiler then took of running again, but I can't tell if power is going anywhere until the capacitor "tick's over to 2M. (hope that make sense)

http://imgur.com/2Hnve68
http://imgur.com/4UwZxbS
http://imgur.com/EewkITw

**Comment by decebaldecebal** [comment]
Power should transfer properly now.The steam boiler can output enough steam for 2 turbines to run at the same time, so if you try with 3, the steam level should go down.
Also if you have a console, you should see some messages from the Copper Pipe network saying how much energy it currently has/transfer. (I left some comments to make fixing of future bugs easier).

**Comment by TheQuadShot** [comment]
Here's a vid of what I'm seeing. The console just keeps repeating the same 3 lines:

[steamcraft.common.tiles.energy.TileCopperWire$EnergyNetwork:updateNetwork:620]: Buffer before7500
[steamcraft.common.tiles.energy.TileCopperWire$EnergyNetwork:updateNetwork:622]: Buffer after7500
[steamcraft.common.tiles.energy.TileCopperWire$EnergyNetwork:updateNetwork:624]: Buffer last7490


http://youtu.be/EqgElQnoae0

Hope this helps

**Comment by decebaldecebal** [comment]
The capacitor can only accept 10 RF/t, while the turbine outputs 20 RF/t and consumes 10 steam/t and the Steam Boiler produces 20 steam/t...So the bottleneck is the Capacitor.I may increase it's input rate cause it just seems useless only accepting 10RF/t...

Also the lines from the energy network explained:
The "before" is RF before input, "after" is after it inputed power and "last" is after it exported power to machines, so you can see that the after is 7500 while the last is 7490, that means that 10 RF was exported to the Capacitor that tick.

**Comment by TheQuadShot** [comment]
Okay, what I don't understand is why the same numbers keep repeating, shouldn't they continue to climb?

**Comment by decebaldecebal** [comment]
Each wire has a capacity of 2500 RF, so it should cap at 7500 RF if you have 3 wires.It is only the energy in the network that is printed.

**Comment by decebaldecebal** [comment]
Everything related to this should be fixed.
