### ISSUE TITLE
[minor] Charger "gauge" doesn't render level of charge.

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#265]
![2015-06-24_00 06 48](https://cloud.githubusercontent.com/assets/11265900/8324896/8e38f1c4-1a09-11e5-92be-bb1f972da312.png)

**Comment by decebaldecebal** [comment]
Actually fixed in 2c2d8cdf1ad7f678319a3fa80f409744a301de57
