### ISSUE TITLE
[minor] Not sure about this, charger rendering "pulses"?

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#266]
Here's a quick vid of it, it's easier to see in full screen
http://youtu.be/JJ6cpKlkNbw

**Comment by decebaldecebal** [comment]
It's because of the bounding box on the Copper Wire.Not sure there is anything to do to fix it because it seems to be a MC thing...

**Comment by TheQuadShot** [comment]
I just noticed this, If you can only see one side of the block, it doesn't flutter, but if you can see 2 or 3 sides, it does.

**Comment by decebaldecebal** [comment]
I can not do anything about this, it's the way MC handles bounding boxes...
