### ISSUE TITLE
Obsidian drill treats slate like it's obsidian (takes a loooong time to break the block)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#267]
it's take the same amount of time to break slate as it does obsidian.
The steam drill does fine.

**Comment by warlordjones** [comment]
Specifically the obsidian drill? Wierd....

**Comment by warlordjones** [comment]
Remember Mr Quad Shot, the more info needed is only for stuff that I need to investigate further :P

**Comment by TheQuadShot** [comment]
LOL, okay, it there a way you can assign it to me so I know it's me that needs to or can do for you?

**Comment by warlordjones** [comment]
I'll @ mention you if there's more info I need from you :)

**Comment by decebaldecebal** [comment]
Fixed in a84ac11844795dd70bd975bbb85b680d85dabb18
