### ISSUE TITLE
Drill's use same amount of "energy" to break any block. (balance issue?)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#268]
The steam drill uses 200mB no matter what block type I break, I tested on 9 blocks (in 3x3) on the following blocks:
Lead, Yellowrite, Stone, Obsidian.

With the electric drill its about .5k on each of the same.

On one hand, I like it that way. On the other, If I'm using the drill longer, it should "cost" more. Does that make sense?

**Comment by warlordjones** [comment]
I think I'm going to keep it this way for now, I may change it in the future.

Other than gamebreaking issues, I'm not going to be looking at balance too much during the beta stage
