### ISSUE TITLE
[crash] Crash to launcher when breaking combustion boiler with steam in it.

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#270]
If you break the combustion boiler that has steam in it you crash, it doesn't crash if it just has water or just coal in it. The block is gone when I re-log and I have a copper tank in my inventory. I couldn't test the nuclear-fired boiler, no recipe.
http://pastebin.com/31P0du5t

**Comment by warlordjones** [comment]
I need to remove a half-broken feature to fix that, shouldn't take long. 

Crap, did I forget a recipe for the nuclear boiler? D:

**Comment by WolfieWaffle** [comment]
Yep, in fact I was going to report that but I forgot ._.
