### ISSUE TITLE
Steam powered axe doesn't break wood any faster than "open" hand

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#271]
it take about 14 hits with bare/open hand and same with steam powered axe.

**Comment by warlordjones** [comment]
Bah. I need to investigate tools too >.>

**Comment by TheQuadShot** [comment]
I've tested all of the steam tools and sword and they all look good, I'm starting to do the drill's now.

**Comment by TheQuadShot** [comment]
All of the drill's are broke in one way or the other. the list is pretty extensive..they either  break the block like they can mine it, but don't produce the ore, or they don't do anything to the ore, (like breaking obsidian by hand) and they all have a problem with slate.

**Comment by decebaldecebal** [comment]
I'll take a look at tools.I have a lot of custom tools in my mod and I think I know how to fix them.

**Comment by WolfieWaffle** [comment]
The sword only does 4 damage, which I think it should at LEAST do as much
damage as a stone sword considering it's metal. Is it supposed to do more
damage with a steam canister?

**Comment by TheQuadShot** [comment]
I would hope so ;-) I kind of expected it to be a bit better than an Iron ax (not the Tcon ax).

**Comment by warlordjones** [comment]
Yeah, steam tools only function properly with a canister in your inventory.

**Comment by TheQuadShot** [comment]
I had 3 full canisters in my inventory and on mouse over it say's "Canister Detected: True"

**Comment by warlordjones** [comment]
Ok, so its detecting the canister properly, but that's not doing anything...yep, sounds like something is borked.

**Comment by decebaldecebal** [comment]
The title issue has been fixed in c8837384f9462043744a7dcef851a6261eb263f7
