### ISSUE TITLE
[minor] wire transfers power to battery but doesn't appear to "connect" to top. (bounding box?)

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#272]
![2015-06-24_05 33 28](https://cloud.githubusercontent.com/assets/11265900/8329971/e6a61534-1a32-11e5-87ce-1fa818ecff26.png)

**Comment by decebaldecebal** [comment]
The Battery model is smaller than a full block, and the wires only render in their block space.The battery model could be made bigger so it is a full block tall.

**Comment by TheQuadShot** [comment]
Maybe this should be tagged as an enhancement?

**Comment by warlordjones** [comment]
Right, yeah, I need to redo the battery bank model

**Comment by warlordjones** [comment]
Same thing is happening with the copper tank. Hmm.

**Comment by warlordjones** [comment]
Ah, this is a dupe of #226 actually. Closing newer as usual.
