### ISSUE TITLE
Cannot transfer power from battery to capacitor

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#273]
I have a lightning rod going into a battery, I watch lightning hit the lightning rod, and the battery is full. the battery is then connected to a capacitor, and power won't transfer to it. If I wire a Tesla coil to the battery it drains pretty quick (by the time I clear the weather and get to it it's empty)

**Comment by warlordjones** [comment]
Bah, I probably broke the capacitor code >.>
