### ISSUE TITLE
Tesla coil doesn't appear to be working. 

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#274]
Here's a screen shot of the test, I watched lightning hit 3 times (2 about 3 seconds apart and the third about 10 seconds later), cleared the weather and they are still alive, I was expecting them to be dead, but they don't appear to be hurt at all. So I did it again standing where I could see. Does the coil need more power than 3 lightning strikes to work? I stood as close as I dare (lightning struck next to me, and I had to change my underwear! lol so I backed off to about 16 blocks and under a roof) and I didn't see any particles around the coil, but I may have been too far away to see it.
![2015-06-24_05 46 10](https://cloud.githubusercontent.com/assets/11265900/8330380/d8ebf4ec-1a35-11e5-947b-9981da759c92.png)

**Comment by warlordjones** [comment]
I'll test it :)
