### ISSUE TITLE
Clockwork wings don't appear to glide properly

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#276]
as far as I can tell, I free fall at the same rate as I do when I hold the sneak key. and I don't move forward, like I expected. (like with the hang-glider from open blocks)

**Comment by warlordjones** [comment]
Bah, that was also working a while ago. Everything is borken! D;

**Comment by decebaldecebal** [comment]
The wings work as intended.The effect when you hold down SHIFT is pretty noticeable.
