### ISSUE TITLE
[minor] Inverted cast iron lamp doesn't work with redstone signal

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#284]
The "normal" lamp works fine (turn on/off) with redstone signal.

**Comment by WolfieWaffle** [comment]
It also does not have a recipe

**Comment by decebaldecebal** [comment]
It has, it is a normal lamp plus a redstone torch.There are 2 versions of the lamp in NEI, and only one of them has a recipe because the other versions is the "lit" state.

**Comment by WolfieWaffle** [comment]
Oh, maybe I just don't have the right version :P
