### ISSUE TITLE
Recipes of various things (and some recommendations and complaints)

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#285]
Shouldn't the grating for the intake block use iron instead of steel?I don't think that you should need to go to the nether to craft that block and start with energy machines.

Also, the steam powered turbine should be made out of iron, the fans and the generator out of iron sheets?Seems to me that the turbine is simply too expensive for generating only 20 RF/t.It is an early game block and the base of starting out with energy machines.

Shouldn't the battery bank have a power core in it's recipe?

Also, the electric jars need a recipe since they are used in the power core recipe and are required for the battery bank to be useful.

And why are there so many useless parts like all the washers, bolts, bearings and nuts?Don't you think that having so many parts is going to make things and recipes very complicated?

Anyways...These are just some ideas that came to me while working on the mod :P

**Comment by warlordjones** [comment]
All of those changes sound pretty reasonable...

**Comment by warlordjones** [comment]
I feel like having a power core in the battery bank recipe may make it too expensive. Hrm
