### ISSUE TITLE
Copper Tank doesn't render properly in inventory or in world

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#286]
In inventory in renders some weird artifacts and in the world it renders OK, but with those artifacts.

If you remove all the rendering code from the TileCopperTankRenderer class, it still renders those artifacts.Maybe I forgot to register something or I've derped something up cause I swear all I did was to copy the renderers from Copper Pipes...

**Comment by warlordjones** [comment]
Funky. I'll take a look.
