### ISSUE TITLE
Add mob functionality to Statis Field

### ISSUE THREAD

**Issue by TheQuadShot** [BrassGoggledCoders/SteamCraft2#291]
I tried dropping a cow next to it, and on it. I also tried to add a redstone signal with the same result.

**Comment by MyDeloreanWontStart** [comment]
It keeps items from despawning methinks, not mobs

**Comment by warlordjones** [comment]
Yeah, only items currently. I could extend it to mobs actually...

**Comment by TheQuadShot** [comment]
I just retested this with an item, and it de-spawned. I dropped some TCon jerky next to it and checked it after 10 minutes and it had de-spawned

**Comment by warlordjones** [comment]
D:

**Comment by warlordjones** [comment]
I'll reopen this to remind me to add mob functionality :) Nice work on the fix tho

**Comment by warlordjones** [comment]
entityAge is private for living entities, no can do.

**Comment by WolfieWaffle** [comment]
So does it have mob functionality or not? Also, I think the brass ingot texture might a a random transparent pixel in the top right corner that is visible when dropped in the world.

**Comment by WolfieWaffle** [comment]
Speaking of brass ingots, I think that 3 for a single log is a bit much, but that's just my opinion.

**Comment by WolfieWaffle** [comment]
I'm back :P are there any textures or new features to bugtest?

**Comment by warlordjones** [comment]
No, no mob functionality, I can't implement it. 

Not much new features, I've only just regained the ability to develop.

**Comment by MrIbby** [comment]
Does an access transformer count as "icky coremodding"?

**Comment by decebaldecebal** [comment]
That could work, but personally I do not see a point in having mobs not despawn...They only do if there isn't a player near them...

**Comment by warlordjones** [comment]
True

**Comment by WolfieWaffle** [comment]
I know that Minefactory Reloaded has jailer's safari nets, which make mobs not despawn. MOb functionality doesn't seem like too important though, I agree.

**Comment by warlordjones** [comment]
Its easy to make mobs never despawn, but to stop them despawning only while they are in the field is not easy.
