### ISSUE TITLE
Teacup overrides Clay Bucket

### ISSUE THREAD

**Issue by themalkav** [BrassGoggledCoders/SteamCraft2#292]
In iguana Tweaks for Tinkers the clay buckets recipes keeps getting overwritten with teacup recipe. Is there a alt recipe that can be turned on in the config(maybe 2 clay in a line) as a option.

v/r
Coffee_Nutz

**Comment by decebaldecebal** [comment]
Maybe we could change the recipe to have at the bottom instead of clay, a bowl?
It seems somewhat logical...

**Comment by warlordjones** [comment]
Bah, I just can't get this recipe right, can I :P

**Comment by warlordjones** [comment]
I'll think about what to change this to

**Comment by themalkav** [comment]
That'd be awesome cause I'm in the middle of building a Modpack centered
around technomancy and steampunk, and was looking at around August
finishing it and so far its the only hiccup in the design. Maybe 4 clay in
a v formation or 2 clay in a stick formation. Use the bowl as a tool
surrounded by clay and you get the bowl back? then cook the teacup to
harden it. Maybe a whole fine china making process with a fire blast
furnace and go ape poop wild with it .

v/r
Coffee_Nutz
I'll send a link to the Youtube series once it starts if you'd like. :)
Cheers' Mate'

**Comment by warlordjones** [comment]
Sounds a bit overcomplex :P I'd like to see the youtube series, yea

**Comment by themalkav** [comment]
Currently the test mod pack is up on technic launcher under the title 13 Cups of Coffee. Not the final product yet but you can take a gander if you so desire, once I finish building the server and finalize I'll start recording and send you the links :)

v/r
Coffee_Nutz


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by themalkav** [comment]
http://www.technicpack.net/modpack/endercrusades.288126

Just updated it for the Mod list as of Current. Still debating on
adding/subtracting Metallurgy/MooFluids/RailCraft/Buildcraft into the final
design. Oh, thank you for addressing the Teacup issue and if you need
ideas... I've got a bunch (I've only recently started to learn your mod so
I'll be stumbling in the dark at first with it)

**Comment by warlordjones** [comment]
I've got a seven page todo list, but I'm always happy to add more stuff :P
