### ISSUE TITLE
[Suggestion] Grindstone ingot Compatibility

### ISSUE THREAD

**Issue by NullMagic** [BrassGoggledCoders/SteamCraft2#299]
So, I really like the Grindstone, like really super love it, it's the easiest way to turn ingots back into dusts without the grind of running them through the various machines that turn ingots into dust. The only complaint I have is that it only does materials found already in Steamcraft, which is reasonable because it's part of SC2 and all. But it'd be really awesome if I could use it on other materials such as Nickel and Platinum etc. So I'd like to suggest allowing it to register dust recipes that exist in other mods such as Another One Bites the Dust, Thermal Expansion, and Tinker's Construct.

**Comment by warlordjones** [comment]
I'll think about the best way to implement this.
