### ISSUE TITLE
The modular masterlist. 

### ISSUE THREAD

**Issue by warlordjones** [BrassGoggledCoders/Steamcraft2#302]
The great big todo list for all things module related...
---
General:
- [ ] Rewrite incompatability, power and steam consumption systems
- [ ] onModuleAdded/onModuleRemoved and onArmourEquipped/Unequipped events that are passed to modules
- [ ] Functional weight system (Armor Only)
- [ ] Redo recipes
- [ ] Better method for module removal
- [ ] Modular Armor/Fist model changes based on module. Allow module to set texture, model part and model position.
- [ ] Brass Fist Module Types: right click, ontick(?), attack modifier, tool, onblockbreak
- [ ] Brass fist will need some way to select between active modules - shift rightclick cycles between rightclick modules?

---
Armor Modules:
- [ ] Last resort
- [ ] Integrated Steam/Electric Canister
- [ ] Item Charger.
- [ ] Energy Shield
- [ ] Portable Lightning Rod and tesla coil
- [ ] Movement based charging
- [ ] Projectile deflection shield
- [ ] Cruise Control
- [ ] Something that destroys configurable items on pickup. Version for the Fist?
- [ ] Wearable Sponge
- [ ] Drill suit
- [ ] module that hides the armour model
- [ ] Fall damage reduction
- [ ] Apiarist Module
- [ ] Sky's Neato integrated armor module idea
- [ ] Standard monocle in module form
- [ ] Boiler Module
- [ ] Module that sucks up liquids you stand in.
- [ ] Crater Boots
- [ ] Ore Sensor (Helmet)
- [ ] Night vision (Helmet)
- [ ] Health points overlay (Helmet)
- [ ] Automatic torch placing module

---
Brass Fist Modules:
- [ ] Electrical Bolt Launcher (Built in,weaker lightning gun)
- [ ] Block pickup with Right-Click
- [ ] Piston-Assisted Punch - Knockback + bit of damage
- [ ] Electrified Fist - Damage increase and DOT?
- [ ] Steam Vent - AOE damage
- [ ] Extendohand - increases reach
- [ ] Integrated Brass Knuckles. Straight up damage.
- [ ] Integrated versions of all steam tools, including drill. Also spanner, shears and flint n steel
- [ ] Integrated Rocket Launcher and/or Rifle? XD
- [ ] Spacewarp Cannon: fires Field Distorters
- [ ] Portable crafting table

**Comment by decebaldecebal** [comment]
Oh nice, sadly I can't help with any of it...At least for a while...

**Comment by warlordjones** [comment]
No problemo, this is mostly for @SkySom :)

**Comment by SkySom** [comment]
Yes all the plans...

**Comment by WolfieWaffle** [comment]
This looks cool :)

**Comment by warlordjones** [comment]
:D

**Comment by SkySom** [comment]
See https://github.com/BrassGoggledCoders/ModularArmor/issues/1
