### ISSUE TITLE
Thaumcraft Support: Native clusters don't smelt into more than one ingot

### ISSUE THREAD

**Issue by Febilian** [BrassGoggledCoders/SteamCraft2#310]
Native Aluminum Cluster and Native Zinc Cluster don't appear to smelt into more than one ingot each, according to NEI. I'm using the latest build from Jenkins(B4.5.89), and I'd noticed this in some previous versions of the mod as well.

To my knowledge, Thaumcraft's Native Clusters are supposed to *double* the output of the ore they're based on. Other clusters from Thaumcraft 4 itself and other mods that add cluster support consistently show the smelting output as 2 ingots per cluster via NEI in my setup, not 1 ingot like Steamcraft 2's versions.

**Comment by warlordjones** [comment]
*facedesk* Easy fix...
