### ISSUE TITLE
Some item textures appear to be swapped

### ISSUE THREAD

**Issue by Febilian** [BrassGoggledCoders/SteamCraft2#314]
I'm just looking at my creative inventory using build 90 from Jenkins, and it appears that the textures for Uranium, Uranium Pellets, and Sulfuric Acid are a bit messed up.

Uranium seems to have the texture that would fit sulfuric acid, uranium pellets has the old 'uranium' texture that's similar to green coal, and sulfuric acid looks like previous versions' uranium pellets.

Their functionality does not appear to be altered in any way, but unless the textures were intended to be swapped around several versions ago, I thought this would be worth bringing up.

Also related on some item-and-texture based confusion, the ores that drop items are mixed up as well. Uranite ore drops sulfuric acid(which looks like uranium pellets), phosphate drops uranium pellets(which look like just uranium), and brimstone drops phosphorous(which actually looks normal! green powdery stuff, it is...)

**Comment by warlordjones** [comment]
Ah crap. Whoops! I fixed the naming in my local dev, but I forgot to change ore drops. I'll do that now
