### ISSUE TITLE
[bug] Phosphate ore drops uranium...

### ISSUE THREAD

**Issue by WolfieWaffle** [BrassGoggledCoders/SteamCraft2#316]
I don't know what's causing this, but on build 90, I mined phosphate ore and got uranium pellets.

**Comment by warlordjones** [comment]
This one is fixed in the dev branch. I'll pull it in in a moment to trigger a jenkins build.

**Comment by warlordjones** [comment]
Should be fixed in build 91

**Comment by WolfieWaffle** [comment]
Thanks!

**Comment by warlordjones** [comment]
NP :D
