### ISSUE TITLE
Steam Tool crash

### ISSUE THREAD

**Issue by vagaprime** [BrassGoggledCoders/SteamCraft2#317]
So I just created a Steam hoe and my game crashed. Here is the client and server cash logs

http://pastebin.com/xF7NtsLj

http://pastebin.com/eygztx70

Edit: I am running the current version listed on Curseforge.

**Comment by warlordjones** [comment]
Could you confirm if this crash still occurs with the latest jenkins build? I cannot reproduce it in dev...

**Comment by vagaprime** [comment]
Crafting the hoe does not crash the game anymore but it only dirt blocks

**Comment by warlordjones** [comment]
Good to hear it doesn't crash. I'll look into it only being able to till dirt blocks (I presume that's what you meant?)

**Comment by vagaprime** [comment]
Ya the hoe will not till the grass blocks only dirt blocks.
