### ISSUE TITLE
Unknown Crash at pack launch using 4.5.90

### ISSUE THREAD

**Issue by vagaprime** [BrassGoggledCoders/SteamCraft2#318]
I just tried updating to the latest version of the mod from the jenkins and i am getting a start up crash.

http://pastebin.com/Zp9C6e33

Edit: The crash is happening with ever version of the mod that i picked up off of the jenkins page.

**Comment by WolfieWaffle** [comment]
I got this too, I think you also have to get the Jenkins boilerplate. I
didn't know it existed, but yeah just click on the warlordjones author link
thing on jenkins and you should be able to find boilerplate from there.

**Comment by warlordjones** [comment]
Yes, you should always grab the jenkins boilerplate too. I'll add a note in the readme about that...

**Comment by vagaprime** [comment]
It is not causing a crash with the latest jenkins build.

**Comment by warlordjones** [comment]
Good, I'd recommend using those until Beta5 releases. They should be somewhat stable.
