### ISSUE TITLE
Mod Relicensing

### ISSUE THREAD

**Issue by warlordjones** [BrassGoggledCoders/Steamcraft2#319]
Asie is attempting once again to obtain the relevant permissions to move Buildcraft off the MMPL, and I believe we should move too (for all mods) Therefore, I need to obtain permissions to change the license from all contributing parties.
- Code: [MIT](https://opensource.org/licenses/MIT)
- Assets: [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)

As such, could anyone on this list respond to this issue with a statement giving your permission for the license change:
- [x] @Spawck 
- [x] @SkySom 
- [x] @decebaldecebal 
- [x] @WolfieWaffle 
- [x] @MrIbby 
- [x] @Chocohead 
- [x] @frothiny 
- [x] @wierdude1999 
- [x] @Joccob 

Thanks in advance,
warlordjones

**Comment by warlordjones** [comment]
I can't spell :P

**Comment by decebaldecebal** [comment]
Fine by me :+1:

**Comment by Joccob** [comment]
I'm ok with that

**Comment by SkySom** [comment]
Already had Moatcarts at MIT due to it being ExtraCarts license. So I'm happy to hear that SteamCraft2 will have the same. You got my support.

**Comment by warlordjones** [comment]
Cheers :D

**Comment by MrIbby** [comment]
I'm fine with the change; hopefully everyone else is around to give consent. (A checklist might be helpful.)

**Comment by warlordjones** [comment]
Time to hunt down those who haven't yet noticed this.

**Comment by warlordjones** [comment]
Permission from Surseance/Spawck get. 
![untitled](https://github-cloud.s3.amazonaws.com/assets/3331837/10565697/15d3069e-75cf-11e5-8852-61c8aea87451.png)

**Comment by warlordjones** [comment]
wierdude9999 has *not* granted permission, and in fact would prefer the assets be relicensed to an attribution based licence, with alterations, and in fact didn't know that the MMPL didn't do this (through no fault of my own) As such, I'll relicense assets to CC, http://creativecommons.org/licenses/by-sa/4.0/ specifically.

**Comment by MrIbby** [comment]
Just FYI: there are multiple CC licenses, so make sure you clearly specify which one.

**Comment by warlordjones** [comment]
I know, the linked one is the one Snurly ones, the sticky attribution one.

**Comment by MrIbby** [comment]
Since you're changing the license, does that mean you'd need to get everyone's permission again?

**Comment by warlordjones** [comment]
Nope, only the asset creators will need to give permission. Code will still be going under MIT.

**Comment by MrIbby** [comment]
Oh oops, didn't see the "assets" part...

**Comment by warlordjones** [comment]
lol

**Comment by WolfieWaffle** [comment]
What is this exactly? Do I need to do something? Sorry, I don't exactly know what's happening.

**Comment by MrIbby** [comment]
We need your consent to change licenses.

Currently, Steamcraft 2 is licensed under the [MMPL](https://github.com/BrassGoggledCoders/SteamCraft2/blob/dev/LICENSE). However, we are in the process of changing the licenses for code and assets to the [MIT License](https://opensource.org/licenses/MIT) and the [CC BY-SA 4.0 License](http://creativecommons.org/licenses/by-sa/4.0/), respectively.

**Comment by WolfieWaffle** [comment]
Well, I give my consent if that's all I need to do. If I need to give it in a certain place, just give me the link :)

**Comment by MrIbby** [comment]
I believe that's all we need, thanks.

**Comment by warlordjones** [comment]
That is indeed, thanks Ibby for clarifying that :)

**Comment by TheDoctorSoda** [comment]
Has this gone through yet? If not, are the remaining people who haven't agrees yet's code/assets replaceable?

**Comment by warlordjones** [comment]
Frothiny literally did the raygun texture an that's it, so yes. I might have permission from him actually, need to check.

Chocohead did a few spelling fixes and that's it...so yes for him. Tbh I probably don't really need to get his permission, but I want to anyway, for completeness. 

wierdude1999 not so much, most of the textures are his. He's not been on for a while. I'll chase it up when I get a chance.

**Comment by TheDoctorSoda** [comment]
Alright. I think we should have this resolved before the new year. We can always throw in temporary assets until we get permissions from weirdude.

**Comment by SkySom** [comment]
Or just re license the code for now and wait on assets

**Comment by TheDoctorSoda** [comment]
That would probably be the best option.
