### ISSUE TITLE
Freezing game: unable to play unknown soundevent steamcraft intake

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#322]
Hi there again! 

Every once in a while in the midst of playing my custom modpack my game suddenly goes all laggy and eventually freezes up completely, resulting in needing to force crash the game in order to restart. I can't tell for sure if it's related to any specific action or not. Checking out the MultiMC log reads a spam of this before I crash it:

[Client thread/WARN]: Unable to play unknown soundEvent: steamcraft:intake

Pastebin of my modlist if it helps: http://pastebin.com/rjJrJLxA

**Comment by SkySom** [comment]
Hmmm... Looks like perhaps, it's not defined in the sounds.json Will have to take a closer look tomorrow.

**Comment by HCSarise** [comment]
So this time the freeze up happened after breaking a logistics pipe. Have no idea if the two events are related.

**Comment by SkySom** [comment]
Do you have an intake somewhere near?

**Comment by HCSarise** [comment]
I have two: one approximately 40 blocks away feeding into an open blocks tank that's feeding a syngas producer (advanced generators) through logistics fluid pipes, and another one approximately 60 blocks away that doesn't have any water beneath it and isn't do anything at the moment. However this error doesn't happen in the same place every time.

**Comment by HCSarise** [comment]
Happened again when trying to remove the crafting sign on a logistics crafting pipe. Wonder if it has something to do with facades/microblock type stuff? It may not even be a problem on your end, though I don't know.

**Comment by warlordjones** [comment]
hey @HCSarise can you confirm if this still occurs with Beta5.0.0?

**Comment by HCSarise** [comment]
Doesn't seem to be an issue anymore, thanks! :)
