### ISSUE TITLE
Sulfuric Acid registered as "ingotUranium" in the OreDictionary

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#323]
There seems to be a bit of a typo in steamcraft.common.compat.CompatabilityLayer

```java
		OreDictHelper.registerOre("ingotUranium", InitItems.itemResource, 2);
		OreDictHelper.registerOre("pelletUranium", InitItems.itemResource, 3);
```
In game, Steamcraft2:ItemResource:2 is Sulfuric Acid not Uranium. ingotUranium should be a meta value of 3 and pelletUranium should be 4.

**Comment by warlordjones** [comment]
Easier to fix than find.
