### ISSUE TITLE
Iron golems that die to fire drop cast iron ingots, rather than normal iron

### ISSUE THREAD

**Issue by TheDoctorSoda** [BrassGoggledCoders/SteamCraft2#327]

**Comment by warlordjones** [comment]
That's a cool idea :D

**Comment by TheDoctorSoda** [comment]
Hmm. That is true...what if there was a way to turn cast iron back into iron somehow?

**Comment by warlordjones** [comment]
Sounds cool - how though? :D

**Comment by TheDoctorSoda** [comment]
Don't know :P

**Comment by TheDoctorSoda** [comment]
Hmm maybe I could make a reddit post and see what people think about it. We can use that to determine whether to have it on be default or not

**Comment by warlordjones** [comment]
Could do, I'm not sure it's an incredibly important feature though XD

**Comment by TheDoctorSoda** [comment]
lol true, but it would break iron farms.

**Comment by TheDoctorSoda** [comment]
maybe not important, but it has the potential to impact something

**Comment by warlordjones** [comment]
True. I say go enabled by default.

**Comment by WolfieWaffle** [comment]
I support as long as there's a config option to turn it off. Non-disposable features that break things are one of the main reasons I don't include mods in modpacks, but I really love extra things like that when they're configurable. Also why not make it drop cast iron when they're killed by lave OR fire? I mean they're both heat, I don't think they'res anything specific saying that cast iron HAS to be made with fire.

**Comment by warlordjones** [comment]
Yep, there's a config. If it dies to lava it should still drop cast iron, since I think lava deals 'fire' damage anyway.

**Comment by TheDoctorSoda** [comment]
Yup, I was using lava to test it. It just checks if they were burning when they drop items.

**Comment by warlordjones** [comment]
Commit for this is pulled over to master now, so I'll close this. Still trying to figure out how exactly I want to handle the dev branch/master branch/release thing in regards to issues.
