### ISSUE TITLE
Crash on entering the deeps

### ISSUE THREAD

**Issue by Adraxas** [BrassGoggledCoders/SteamCraft2#331]
http://pastebin.com/CCdCZgBx

**Comment by TheDoctorSoda** [comment]
Yeah, the deeps have a lot of issues right now. I would recommend disabling it in the configs until we get it all sorted out ;)

**Comment by Adraxas** [comment]
it works fine as long as i don't enter the portal, so i just wont do that.

**Comment by warlordjones** [comment]
Huh, that's a new one. I'm keeping #282 as the master for all deeps-related issues, so I'll close this.

**Comment by Adraxas** [comment]
from looking at the other crashes, this one seems to be different

**Comment by warlordjones** [comment]
It is, and thanks for reporting it. But #282 is the masterlist for this, and so I closed this one.

**Comment by Adraxas** [comment]
wasn't asking you to. just making sure
