### ISSUE TITLE
Blue slate blocks have all screwed up ore dictionary names.

### ISSUE THREAD

**Issue by TheDoctorSoda** [BrassGoggledCoders/SteamCraft2#333]
Bricks have "cobblestone" entry, cobblestone has "stone" entry, and stone has no entry at all. Blame @warlordjones.

**Comment by warlordjones** [comment]
We might need the 'aronafail' label back XD

**Comment by warlordjones** [comment]
This was apparently fixed in ac10b4be53bf648f4c262a52b1c19d318b2c7ae3

**Comment by TheDoctorSoda** [comment]
Ah, yes. I thought I had tagged this as fixed in dev.
