### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Alaberti** [BrassGoggledCoders/SteamCraft2#338]
Hello,

I keep seeing the following spamming the console:

672 67 3102[16:56:10] [Server thread/INFO] [STDOUT]: [steamcraft.common.tiles.energy.TileCopperWire:updateConnections:256]: Updating connections...
672 67 3102[16:56:10] [Server thread/INFO] [STDOUT]: [steamcraft.common.tiles.energy.TileCopperWire:updateNetwork:365]: Wire network not null.
672 67 3102[16:56:10] [Server thread/INFO] [STDOUT]: [steamcraft.common.tiles.energy.TileCopperWire:updateNetwork:415]: Same network.
672 67 3102[16:56:10] [Server thread/INFO] [STDOUT]: [steamcraft.common.tiles.energy.TileCopperWire:updateConnections:313]: Connections updated

Is it possible to have a config option to turn that on/off? I assume it's for debug purposes but it often makes tracking other issues down a little difficult.

**Comment by decebaldecebal** [comment]
I forgot some debug messages in code.They are now removed in the latest Jenkins build.
