### ISSUE TITLE
Crash on crafting an electric jar

### ISSUE THREAD

**Issue by TheDoctorSoda** [BrassGoggledCoders/Steamcraft2#339]
Forwarding this to you from a friend: http://pastebin.com/GY97g3DD

**Comment by warlordjones** [comment]
Cannot reproduce in dev environment crafting in either a vanilla or Tinker's table.

**Comment by MrIbby** [comment]
Needs testing

**Comment by TheDoctorSoda** [comment]
Closing because it cannot be reproduced and nobody else has reported this.
