### ISSUE TITLE
Notice of Resignation

### ISSUE THREAD

**Issue by TheDoctorSoda** [BrassGoggledCoders/SteamCraft2#340]
I feel that I have been unable help much for the Brass Goggled Coders for the following reasons:

* I am very new to Steamcraft, I do not know how things work as is very well, much less develop on it.
* I do not know the goal of the mod, and what direction you all plan on taking it in.
* I am not nearly as experienced as most if not all of you guys at mosding, or coding in general.
* I have lost almost all interest in modding minecraft in general, and I think I overestimate my capabilities at doing so.
* I do understand that Steamcraft is not the only BGC mod, but most of these points still stand for the rest of them.

So for the reasons above, I officially resign from the Brass Goggles Coders. I am sorry if I have wasted anyone's time.

Have a nice day,
TheDoctorSoda

**Comment by warlordjones** [comment]
Sorry to see you go dude. I'll keep you 'on the payroll' so to speak, in case you happen to want to come back in the future :)

I'm not sure what my goal is either come to think of it, I'm just working through a gigantic internal todo list and occasionally applying a metric tonne of duct tape. Yeah, I'm not really sure :P 

Also, you are about as experienced as me I would have thought, I've been doing it quite a few years without much improvement :P I've no real idea what I'm doing XD 

Thanks for your help, and hope you'll still be around :D

**Comment by TheDoctorSoda** [comment]
Haha, but let's be honest.. .what have I done? Fixed a few of your derps, and replaced an iron golem drop? Hardly a contributing member in my opinion. I also have zero ideas at all for the mod, so there's that too.

**Comment by TheDoctorSoda** [comment]
If I happen to catch another derp, I'll submit a PR :P

**Comment by warlordjones** [comment]
That's still more than some of the people that stick around on the team list :P

**Comment by MrIbby** [comment]
I agree with @warlordjones, you've done a lot more than I have (or at least I think so :P).

Also, I'm available for the whole week, so I should be able to help out.
