### ISSUE TITLE
Change default branch to dev

### ISSUE THREAD

**Issue by MrIbby** [BrassGoggledCoders/SteamCraft2#341]
https://github.com/BrassGoggledCoders/SteamCraft2/settings/branches

Lowers the probability of fails like [this](https://github.com/BrassGoggledCoders/SteamCraft2/commit/b256c1b0317c5a1febdcde3c1f6dd7c59faf44bc) :P

**Comment by decebaldecebal** [comment]
Default branch is not dev and the master branch is now protected.
