### ISSUE TITLE
Crash when while populating chunk.

### ISSUE THREAD

**Issue by fewizz** [BrassGoggledCoders/Steamcraft2#344]
http://pastebin.com/kNGxrhWE

blockMushroom is not registered 
https://github.com/BrassGoggledCoders/Steamcraft2/blob/dev/src/main/java/steamcraft/common/init/InitBlocks.java#L705

https://github.com/BrassGoggledCoders/Steamcraft2/blob/dev/src/main/java/steamcraft/common/worldgen/biomes/DepthsBiomeDecorator.java#L326

**Comment by warlordjones** [comment]
Derp! Will fix ASAP
