### ISSUE TITLE
The 1.8.9 Update

### ISSUE THREAD

**Issue by ProfessorProspector** [BrassGoggledCoders/Steamcraft2#351]
So 1.8.9 is here and growing. I'd say it's best to get on the train before it leaves the station. I'll be perfectly  willing to help, too. First of all, is Boilerplate ported yet? Can't really port it without that.

Right now I'm waiting on @modmuss50 to get [JSON-Destroyer](https://github.com/modmuss50/JSON-Destroyer) ready to be put into projects, but for now I guess we could just include those files within Steamcraft until he gets that all sorted out.

**Comment by modmuss50** [comment]
It's ready, just need to document it

**Comment by TheDoctorSoda** [comment]
Ah, good.

**Comment by modmuss50** [comment]
I can PR it into gradle if you like? Tell me when

**Comment by TheDoctorSoda** [comment]
Yeah I just need to get the grade file set up for 1.8 first.

**Comment by TheDoctorSoda** [comment]
Hmm @warlordjones would you mind trying to update the gradle file on the 1.8.9 branch? I legitimately have no idea how gradle workds :P

**Comment by warlordjones** [comment]
1.8.9? Eww....

I can take a look, if I must.

**Comment by TheDoctorSoda** [comment]
I have no idea what all the things in the gradle file are doing? Where do I update the boilerplate version and where do I update the forge version?

**Comment by warlordjones** [comment]
I'll take a look myself soon.

Wanna hop on IRC? Sky's nearly done the boilerplate port, I think.

**Comment by TheDoctorSoda** [comment]
Sure. What channel?

**Comment by modmuss50** [comment]
I've got some free time over the next week or so. So I can help with the update, what IRC channel do you hang out in?

**Comment by warlordjones** [comment]
#steamcraft2, naturally :P

**Comment by Prospector** [comment]
@modmuss50 Whenever you're available you should be able to PR the library into the build.gradle.

**Comment by SkySom** [comment]
I would like to double down here on saying I'd rather just have us go ahead and do the JSON's rather than work around it by using someone else's library, since so far we have managed to survive without having heavy dependencies on other's software. Of course for the time being this will help us get 1.8.9 out without a lot of additional BS. But I would really prefer we move towards just using JSON, as the end game.

**Comment by modmuss50** [comment]
This dependecie will be automaticly included in your file mod jar so there will be no diffrence to the end user. Feel free to copy the code out of it, if you wish. It doesnt support any custom models(yet) so that might be a limitation for you guys

This isn't my mod so its not my decision if you end up using it but I hope I can help out.

**Comment by SkySom** [comment]
This isn't so much the end user as yes I see that it's shaded. I've just seen wayyy too many people (Especially off this project) just kinda up and poof. So I'm a bit shy to rely on something like that, when the next update you could be gone and we're just kinda up the creek without a paddle.

**Comment by modmuss50** [comment]
That is a good point. But the mod is open source and not that complicated to work with. But I do see where you are coming from.

**Comment by Prospector** [comment]
So the way I'm doing this is basically disabling everything and adding everything back one by one until the entire mod is working. Not sure if that's the best approach or not when porting.

**Comment by SkySom** [comment]
Truthfully the best way would be to get on the trello we've been working on adding stuff to. Thinking it's a good time for an actual rewrite rather than just a in place port.

**Comment by Prospector** [comment]
I completely agree. This mod will never make it out of beta lol

**Comment by FreneticScribbler** [comment]
If you wanna rewrite it, be my guest. I can't stomach it because of all the rewrites we had before the mod's release. Still think it'd be easier to polish than rewrite anyway. Or we could do a MC style rolling rewrite :P

**Comment by SkySom** [comment]
I don't think it'll be a total rewrite. Just pieces. (The deeps being on of those things that just need rewritten rather than trying to fix it constantly)

**Comment by FreneticScribbler** [comment]
That I can deal with.

**Comment by SkySom** [comment]
Yeah I'm not entirely crazy 😜 I know that a full rewrite would happen without burning all of us out. But a small wrote moving stuff around and some stuff to boilerplate wouldn't hurt

**Comment by FreneticScribbler** [comment]
Exactly. See the genericisation of boiler containers I did earlier :D

**Comment by Prospector** [comment]
I keep meaning to work on this but every team I load up the workspace I just get a tonne of inspiration to do everything except for working on this lol

**Comment by FreneticScribbler** [comment]
Lol, no problem, just be sure to push anything you do work on.

**Comment by SkySom** [comment]
@ProfessorProspector just an fyi, you're gonna need to take a look at MoarCarts for how I do all the new Boilerplate stuff. If you have any questions about it. Just ask. But I've changed a lot of how we do things

**Comment by Prospector** [comment]
Ah yes. I never really messed with the old Boilerplate so I guess I just have to learn it once. By the way, this is TheDoctorSoda here, changed the name up. Probably figured that out.

**Comment by Prospector** [comment]
See [Steam Age Revolution](https://github.com/BrassGoggledCoders/SteamAgeRevolution).
