### ISSUE TITLE
Steam-powered drill AoE effect has silk touch on some blocks

### ISSUE THREAD

**Issue by HCSarise** [BrassGoggledCoders/SteamCraft2#358]
Hiya,

I've noticed while mining with the steam-powered drill that it silk touches all the steamcraft stone. Also some random blocks from Ars Magica 2. 

Not sure if that's intended behavior.

**Comment by FreneticScribbler** [comment]
Huh, that's odd, and certainly not intentional....

**Comment by mallrat208** [comment]
This is related to #365

**Comment by SkySom** [comment]
Closing as related to #365
