### ISSUE TITLE
Steamcraft and Microblocks - Issue as per request of decebaldecebal

### ISSUE THREAD

**Issue by HalestormXV** [BrassGoggledCoders/SteamCraft2#359]
Steamcraft seems to crash with Immbis Microblocks on a server. Which is really weird. It works fine on Singleplayer. Here is the crash report that the server is spitting out. I can't make heads or tails of it and trust me I have tried. I can't tell which is causing it. Steamcraft or Immbis. The Immibis Core mod works, but the microblocks mod doesn't.

 Report: http://pastebin.com/HXy3P7H4

As per decebaldecebal on the curse page I am opening this request formally. Reminder, it works fine on Singleplayer, not on the Server.

**Comment by SkySom** [comment]
@decebaldecebal any chance you could take a look at this? I'm going to trying to do a final run through and kill a bunch of critical bugs.

**Comment by raress96** [comment]
@SkySom Not really, I am very busy with irl stuff.
From the log the problem seems to be that somewhere, the TileHatchRenderer is loaded on the server, but it is only a client side class.Putting this in the proxy should hopefully fix the bug.

**Comment by SkySom** [comment]
Alright will take a look myself. Thanks.
