### ISSUE TITLE
Incorrect Ore Dictionary Tags on Metal Blocks

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#360]
Steamcraft 2 version: B5.0.1
Boilerplate version: 6.2.1

It looks like that at some point a few blocks were removed from the mod causing the current oreDictionary registration to be off.

from [steamcraft.common.compat.CompatabilityLayer.java#L198-L200](https://github.com/BrassGoggledCoders/Steamcraft2/blob/dev/src/main/java/steamcraft/common/compat/CompatabilityLayer.java#L198-L200):

```
        OreDictHelper.registerOre("blockUranium", InitBlocks.blockMetal, 4);
        OreDictHelper.registerOre("blockBrimstone", InitBlocks.blockMetal, 5);
        OreDictHelper.registerOre("blockPhosphate", InitBlocks.blockMetal, 6);

```

That should instead be:

```

        OreDictHelper.registerOre("blockBrass", InitBlocks.blockMetal, 4);
        OreDictHelper.registerOre("blockBronze", InitBlocks.blockMetal, 5);
        OreDictHelper.registerOre("blockSteel", InitBlocks.blockMetal, 6);
```

**Comment by SkySom** [comment]
@ProfessorProspector  did you ever take care of this?

**Comment by Prospector** [comment]
Thought I did, but maybe I never pushed it. anyway that repo is long gone :P

**Comment by SkySom** [comment]
Alright will fix it myself then.
