### ISSUE TITLE
Crash on entering Inner Earth Portal

### ISSUE THREAD

**Issue by walkerjonny** [BrassGoggledCoders/SteamCraft2#363]
Is the Inner Earth Portal supposed to be working in the 1.7.10 branch?

Because I'm getting that crash even with the newest working file setup.
http://pastebin.com/NdWEfu0T

**Comment by SkySom** [comment]
Truthfully I thought the Portal was turned off because it was so buggy, and we didn't have time to fix it.

**Comment by walkerjonny** [comment]
Maybe you can make a version where it is turned off then to prevent further issues with it, possibly together with some other important fixes, if necessary. 
Think of it as a final "house cleaning" update to the 1.7.10 branch.

**Comment by FreneticScribbler** [comment]
It should be disabled by default in the most recent builds already?
