### ISSUE TITLE
Steam Drill harvesting blocks incorrectly when activated

### ISSUE THREAD

**Issue by mallrat208** [BrassGoggledCoders/SteamCraft2#365]
Steamcraft2 ver.: 1.7.10-B5.0.1
Boilerplate ver.: 1.7.10-6.2.1

When in 3x3 mode, the Steam Drill is harvesting blocks incorrectly. Rather than dropping what a block should when broken, it is giving you back the block itself meaning any blocks that are determined by TE are given back as the default version of the block. It also has the side effect as acting as Silk Touch for certain modded ores like Thaumcraft Infused Stone.

**Comment by SkySom** [comment]
Also as mentioned, it doesn't fire onBlockBreakEvent. It should

**Comment by FreneticScribbler** [comment]
Fixed. See above.
