### ISSUE TITLE
glPushMatrix/glPopMatrix mismatch... somewhere

### ISSUE THREAD

**Issue by Baughn** [BrassGoggledCoders/SteamCraft2#368]
I have pictures of myself with a cow on my head: https://brage.info/e13/#6

But in all seriousness, there's a rendering bug somewhere. Here's what I know:
- It happens in 'vanilla' TerraFirmaPunk, relatively rarely on world spawn because of Steamcraft spawns through the Ruins mod.
- Players get a lot of GL error 1283 spam, plus rendering glitches like the above, plus occasional multi-second lockups. Some of those glitches are less amusing, too.
- Removing all Steamcraft spawns, using `sed -ri 's/,Steamcraft:[^,]+/,air/g' mods/resources/ruins/*/*` makes the glitches go away. They otherwise happen reliably on seed -1616573171225578786, at one particular location close to spawn. Eh... I can give you coordinates if you want.

I therefore think this is probably a Steamcraft bug. Here's a complete list of the blocks spawned:

```
Steamcraft:blockBrass-0
Steamcraft:boilerOn-5
Steamcraft:chargingPad-2
Steamcraft:engineering-0
Steamcraft:fan-1
Steamcraft:fan-3
Steamcraft:fan-5
Steamcraft:fluidSteamConverter-4
Steamcraft:hammer-2
Steamcraft:hammer-3
Steamcraft:heater-0
Steamcraft:heater-5
Steamcraft:horn-2
Steamcraft:horn-3
Steamcraft:horn-4
Steamcraft:meter-2
Steamcraft:pipe-0
Steamcraft:ruptureDisc-3
Steamcraft:steamTank-0
Steamcraft:vacuum-2
Steamcraft:vacuum-3
Steamcraft:vacuum-4
Steamcraft:vacuum-5
Steamcraft:valvePipe-0
Steamcraft:valvePipe-1
Steamcraft:valvePipe-2
Steamcraft:valvePipe-3
Steamcraft:valvePipe-4
Steamcraft:valvePipe-5
```

Maybe some of these are not valid?

**Comment by Baughn** [comment]
Never mind, it seems I mixed you up with the _other_ mod using that namespace.

**Comment by FreneticScribbler** [comment]
Yep, our modid is "steamcraft", theirs is "Steamcraft" Thank god for case sensitive modids!

**Comment by mallrat208** [comment]
They don't even have Steamcraft anywhere in the mod's name either. It's confusing.
