### ISSUE TITLE
Steam fluid texture derpinness

### ISSUE THREAD

**Issue by decebaldecebal** [BrassGoggledCoders/SteamCraft2#82]
Somebody please take a look at the steam fluid registration because I had to do some tricks to get it to work properly with the rendering code gotten from buildcraft(you can find it in the GuiSteamBoiler class).

Also I tested this with BC and it seems like the steam texture works in pipes but not in the tanks, so there is definitely something fishy on our end...

**Comment by warlordjones** [comment]
I dun fixed this with some hackery.
